// Code generated by qtc from "post.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line pages/forum/post/post.qtpl:1
package post

//line pages/forum/post/post.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line pages/forum/post/post.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line pages/forum/post/post.qtpl:1
func (p *Page) StreamTitle(qw422016 *qt422016.Writer) {
//line pages/forum/post/post.qtpl:1
	qw422016.E().S(*p.post.Title())
//line pages/forum/post/post.qtpl:1
}

//line pages/forum/post/post.qtpl:1
func (p *Page) WriteTitle(qq422016 qtio422016.Writer) {
//line pages/forum/post/post.qtpl:1
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/forum/post/post.qtpl:1
	p.StreamTitle(qw422016)
//line pages/forum/post/post.qtpl:1
	qt422016.ReleaseWriter(qw422016)
//line pages/forum/post/post.qtpl:1
}

//line pages/forum/post/post.qtpl:1
func (p *Page) Title() string {
//line pages/forum/post/post.qtpl:1
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/forum/post/post.qtpl:1
	p.WriteTitle(qb422016)
//line pages/forum/post/post.qtpl:1
	qs422016 := string(qb422016.B)
//line pages/forum/post/post.qtpl:1
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/forum/post/post.qtpl:1
	return qs422016
//line pages/forum/post/post.qtpl:1
}

//line pages/forum/post/post.qtpl:3
func (p *Page) StreamContent(qw422016 *qt422016.Writer) {
//line pages/forum/post/post.qtpl:3
	qw422016.N().S(`<div class="content"><div><h1>`)
//line pages/forum/post/post.qtpl:6
	qw422016.E().S(*p.post.Title())
//line pages/forum/post/post.qtpl:6
	qw422016.N().S(`</h1><p>`)
//line pages/forum/post/post.qtpl:7
	qw422016.E().S(p.rendererService.CreatedBy(p.post, p.language.ID()))
//line pages/forum/post/post.qtpl:7
	qw422016.N().S(`</p>`)
//line pages/forum/post/post.qtpl:8
	if p.IsLoggedIn() && p.user.ID() == p.post.CreatedByID() {
//line pages/forum/post/post.qtpl:8
		qw422016.N().S(`<p><a href="/ForumPost/Delete/`)
//line pages/forum/post/post.qtpl:10
		qw422016.E().S(p.post.ID())
//line pages/forum/post/post.qtpl:10
		qw422016.N().S(`">`)
//line pages/forum/post/post.qtpl:11
		qw422016.E().S(p.Translate("delete"))
//line pages/forum/post/post.qtpl:11
		qw422016.N().S(`</a></p>`)
//line pages/forum/post/post.qtpl:14
	}
//line pages/forum/post/post.qtpl:14
	qw422016.N().S(`<p>`)
//line pages/forum/post/post.qtpl:16
	qw422016.E().S(p.post.Message())
//line pages/forum/post/post.qtpl:16
	qw422016.N().S(`</p></div>`)
//line pages/forum/post/post.qtpl:19
	if len(p.replies) > 0 {
//line pages/forum/post/post.qtpl:19
		qw422016.N().S(`<h2>`)
//line pages/forum/post/post.qtpl:20
		qw422016.E().S(p.TranslatePlural("reply"))
//line pages/forum/post/post.qtpl:20
		qw422016.N().S(`</h2>`)
//line pages/forum/post/post.qtpl:21
		for k := range p.replies {
//line pages/forum/post/post.qtpl:21
			qw422016.N().S(`<div><p>`)
//line pages/forum/post/post.qtpl:24
			if p.replies[k].Title() != nil {
//line pages/forum/post/post.qtpl:25
				qw422016.E().S(*p.replies[k].Title())
//line pages/forum/post/post.qtpl:26
			}
//line pages/forum/post/post.qtpl:26
			qw422016.N().S(`</p><p>`)
//line pages/forum/post/post.qtpl:28
			qw422016.E().S(p.rendererService.CreatedBy(p.replies[k], p.language.ID()))
//line pages/forum/post/post.qtpl:28
			qw422016.N().S(`</p></div>`)
//line pages/forum/post/post.qtpl:30
		}
//line pages/forum/post/post.qtpl:31
	}
//line pages/forum/post/post.qtpl:31
	qw422016.N().S(`</div>`)
//line pages/forum/post/post.qtpl:33
}

//line pages/forum/post/post.qtpl:33
func (p *Page) WriteContent(qq422016 qtio422016.Writer) {
//line pages/forum/post/post.qtpl:33
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/forum/post/post.qtpl:33
	p.StreamContent(qw422016)
//line pages/forum/post/post.qtpl:33
	qt422016.ReleaseWriter(qw422016)
//line pages/forum/post/post.qtpl:33
}

//line pages/forum/post/post.qtpl:33
func (p *Page) Content() string {
//line pages/forum/post/post.qtpl:33
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/forum/post/post.qtpl:33
	p.WriteContent(qb422016)
//line pages/forum/post/post.qtpl:33
	qs422016 := string(qb422016.B)
//line pages/forum/post/post.qtpl:33
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/forum/post/post.qtpl:33
	return qs422016
//line pages/forum/post/post.qtpl:33
}
