// Code generated by qtc from "createupdate.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line pages/admin/domain/createupdate/createupdate.qtpl:1
package createupdate

//line pages/admin/domain/createupdate/createupdate.qtpl:1
import "fmt"

//line pages/admin/domain/createupdate/createupdate.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line pages/admin/domain/createupdate/createupdate.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line pages/admin/domain/createupdate/createupdate.qtpl:3
func (p *Page) StreamTitle(qw422016 *qt422016.Writer) {
//line pages/admin/domain/createupdate/createupdate.qtpl:3
	qw422016.E().S(p.displayTitle)
//line pages/admin/domain/createupdate/createupdate.qtpl:3
}

//line pages/admin/domain/createupdate/createupdate.qtpl:3
func (p *Page) WriteTitle(qq422016 qtio422016.Writer) {
//line pages/admin/domain/createupdate/createupdate.qtpl:3
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/admin/domain/createupdate/createupdate.qtpl:3
	p.StreamTitle(qw422016)
//line pages/admin/domain/createupdate/createupdate.qtpl:3
	qt422016.ReleaseWriter(qw422016)
//line pages/admin/domain/createupdate/createupdate.qtpl:3
}

//line pages/admin/domain/createupdate/createupdate.qtpl:3
func (p *Page) Title() string {
//line pages/admin/domain/createupdate/createupdate.qtpl:3
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/admin/domain/createupdate/createupdate.qtpl:3
	p.WriteTitle(qb422016)
//line pages/admin/domain/createupdate/createupdate.qtpl:3
	qs422016 := string(qb422016.B)
//line pages/admin/domain/createupdate/createupdate.qtpl:3
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/admin/domain/createupdate/createupdate.qtpl:3
	return qs422016
//line pages/admin/domain/createupdate/createupdate.qtpl:3
}

//line pages/admin/domain/createupdate/createupdate.qtpl:5
func (p *Page) StreamContent(qw422016 *qt422016.Writer) {
//line pages/admin/domain/createupdate/createupdate.qtpl:5
	qw422016.N().S(`<main class="content"><h1>`)
//line pages/admin/domain/createupdate/createupdate.qtpl:7
	qw422016.E().S(p.displayTitle)
//line pages/admin/domain/createupdate/createupdate.qtpl:7
	qw422016.N().S(`</h1>`)
//line pages/admin/domain/createupdate/createupdate.qtpl:8
	qw422016.N().S(p.form.Errors())
//line pages/admin/domain/createupdate/createupdate.qtpl:9
	qw422016.N().S(p.rendererService.CreatedUpdatedByLinks(p.GetCoreContext(), p.language.ID(), p.domain))
//line pages/admin/domain/createupdate/createupdate.qtpl:10
	qw422016.N().S(p.form.Open())
//line pages/admin/domain/createupdate/createupdate.qtpl:11
	qw422016.N().S(p.form.Field("_uname"))
//line pages/admin/domain/createupdate/createupdate.qtpl:12
	qw422016.N().S(p.form.Field("_t"))
//line pages/admin/domain/createupdate/createupdate.qtpl:13
	qw422016.N().S(p.form.Field("active"))
//line pages/admin/domain/createupdate/createupdate.qtpl:14
	qw422016.N().S(p.form.Field("site"))
//line pages/admin/domain/createupdate/createupdate.qtpl:14
	qw422016.N().S(`<br>`)
//line pages/admin/domain/createupdate/createupdate.qtpl:15
	qw422016.N().S(p.form.Field("language"))
//line pages/admin/domain/createupdate/createupdate.qtpl:15
	qw422016.N().S(`<br>`)
//line pages/admin/domain/createupdate/createupdate.qtpl:16
	qw422016.N().S(p.form.Field("currencies"))
//line pages/admin/domain/createupdate/createupdate.qtpl:16
	qw422016.N().S(`<br>`)
//line pages/admin/domain/createupdate/createupdate.qtpl:17
	qw422016.N().S(p.form.Field("host"))
//line pages/admin/domain/createupdate/createupdate.qtpl:17
	qw422016.N().S(`<br>`)
//line pages/admin/domain/createupdate/createupdate.qtpl:18
	qw422016.N().S(p.form.CreateUpdateActions("action", fmt.Sprintf("Domain/View?id=%s", p.domain.ID())))
//line pages/admin/domain/createupdate/createupdate.qtpl:18
	qw422016.N().S(`</form></main>`)
//line pages/admin/domain/createupdate/createupdate.qtpl:21
}

//line pages/admin/domain/createupdate/createupdate.qtpl:21
func (p *Page) WriteContent(qq422016 qtio422016.Writer) {
//line pages/admin/domain/createupdate/createupdate.qtpl:21
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/admin/domain/createupdate/createupdate.qtpl:21
	p.StreamContent(qw422016)
//line pages/admin/domain/createupdate/createupdate.qtpl:21
	qt422016.ReleaseWriter(qw422016)
//line pages/admin/domain/createupdate/createupdate.qtpl:21
}

//line pages/admin/domain/createupdate/createupdate.qtpl:21
func (p *Page) Content() string {
//line pages/admin/domain/createupdate/createupdate.qtpl:21
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/admin/domain/createupdate/createupdate.qtpl:21
	p.WriteContent(qb422016)
//line pages/admin/domain/createupdate/createupdate.qtpl:21
	qs422016 := string(qb422016.B)
//line pages/admin/domain/createupdate/createupdate.qtpl:21
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/admin/domain/createupdate/createupdate.qtpl:21
	return qs422016
//line pages/admin/domain/createupdate/createupdate.qtpl:21
}

//line pages/admin/domain/createupdate/createupdate.qtpl:23
func (p *Page) StreamStylesheets(qw422016 *qt422016.Writer) {
//line pages/admin/domain/createupdate/createupdate.qtpl:24
	if p.form.ContainsSelectSearch() {
//line pages/admin/domain/createupdate/createupdate.qtpl:24
		qw422016.N().S(`<link rel="stylesheet" href="/c/a/selectSearch.css"></link>`)
//line pages/admin/domain/createupdate/createupdate.qtpl:26
	}
//line pages/admin/domain/createupdate/createupdate.qtpl:27
}

//line pages/admin/domain/createupdate/createupdate.qtpl:27
func (p *Page) WriteStylesheets(qq422016 qtio422016.Writer) {
//line pages/admin/domain/createupdate/createupdate.qtpl:27
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/admin/domain/createupdate/createupdate.qtpl:27
	p.StreamStylesheets(qw422016)
//line pages/admin/domain/createupdate/createupdate.qtpl:27
	qt422016.ReleaseWriter(qw422016)
//line pages/admin/domain/createupdate/createupdate.qtpl:27
}

//line pages/admin/domain/createupdate/createupdate.qtpl:27
func (p *Page) Stylesheets() string {
//line pages/admin/domain/createupdate/createupdate.qtpl:27
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/admin/domain/createupdate/createupdate.qtpl:27
	p.WriteStylesheets(qb422016)
//line pages/admin/domain/createupdate/createupdate.qtpl:27
	qs422016 := string(qb422016.B)
//line pages/admin/domain/createupdate/createupdate.qtpl:27
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/admin/domain/createupdate/createupdate.qtpl:27
	return qs422016
//line pages/admin/domain/createupdate/createupdate.qtpl:27
}

//line pages/admin/domain/createupdate/createupdate.qtpl:29
func (p *Page) StreamJavascripts(qw422016 *qt422016.Writer) {
//line pages/admin/domain/createupdate/createupdate.qtpl:29
	qw422016.N().S(`<script src="/j/a/cu.js"></script>`)
//line pages/admin/domain/createupdate/createupdate.qtpl:31
	if p.form.ContainsSelectSearch() {
//line pages/admin/domain/createupdate/createupdate.qtpl:31
		qw422016.N().S(`<script src="/j/a/selectSearch.js"></script>`)
//line pages/admin/domain/createupdate/createupdate.qtpl:33
	}
//line pages/admin/domain/createupdate/createupdate.qtpl:34
}

//line pages/admin/domain/createupdate/createupdate.qtpl:34
func (p *Page) WriteJavascripts(qq422016 qtio422016.Writer) {
//line pages/admin/domain/createupdate/createupdate.qtpl:34
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/admin/domain/createupdate/createupdate.qtpl:34
	p.StreamJavascripts(qw422016)
//line pages/admin/domain/createupdate/createupdate.qtpl:34
	qt422016.ReleaseWriter(qw422016)
//line pages/admin/domain/createupdate/createupdate.qtpl:34
}

//line pages/admin/domain/createupdate/createupdate.qtpl:34
func (p *Page) Javascripts() string {
//line pages/admin/domain/createupdate/createupdate.qtpl:34
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/admin/domain/createupdate/createupdate.qtpl:34
	p.WriteJavascripts(qb422016)
//line pages/admin/domain/createupdate/createupdate.qtpl:34
	qs422016 := string(qb422016.B)
//line pages/admin/domain/createupdate/createupdate.qtpl:34
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/admin/domain/createupdate/createupdate.qtpl:34
	return qs422016
//line pages/admin/domain/createupdate/createupdate.qtpl:34
}
