// Code generated by qtc from "login.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line pages/account/login/login.qtpl:1
package login

//line pages/account/login/login.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line pages/account/login/login.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line pages/account/login/login.qtpl:1
func (p *Page) StreamStylesheets(qw422016 *qt422016.Writer) {
//line pages/account/login/login.qtpl:1
	qw422016.N().S(`<link rel="stylesheet" href="/c/simpleBox.css">`)
//line pages/account/login/login.qtpl:1
}

//line pages/account/login/login.qtpl:1
func (p *Page) WriteStylesheets(qq422016 qtio422016.Writer) {
//line pages/account/login/login.qtpl:1
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/account/login/login.qtpl:1
	p.StreamStylesheets(qw422016)
//line pages/account/login/login.qtpl:1
	qt422016.ReleaseWriter(qw422016)
//line pages/account/login/login.qtpl:1
}

//line pages/account/login/login.qtpl:1
func (p *Page) Stylesheets() string {
//line pages/account/login/login.qtpl:1
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/account/login/login.qtpl:1
	p.WriteStylesheets(qb422016)
//line pages/account/login/login.qtpl:1
	qs422016 := string(qb422016.B)
//line pages/account/login/login.qtpl:1
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/account/login/login.qtpl:1
	return qs422016
//line pages/account/login/login.qtpl:1
}

//line pages/account/login/login.qtpl:3
func (p *Page) StreamTitle(qw422016 *qt422016.Writer) {
//line pages/account/login/login.qtpl:3
	qw422016.E().S(p.Translate("login"))
//line pages/account/login/login.qtpl:3
}

//line pages/account/login/login.qtpl:3
func (p *Page) WriteTitle(qq422016 qtio422016.Writer) {
//line pages/account/login/login.qtpl:3
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/account/login/login.qtpl:3
	p.StreamTitle(qw422016)
//line pages/account/login/login.qtpl:3
	qt422016.ReleaseWriter(qw422016)
//line pages/account/login/login.qtpl:3
}

//line pages/account/login/login.qtpl:3
func (p *Page) Title() string {
//line pages/account/login/login.qtpl:3
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/account/login/login.qtpl:3
	p.WriteTitle(qb422016)
//line pages/account/login/login.qtpl:3
	qs422016 := string(qb422016.B)
//line pages/account/login/login.qtpl:3
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/account/login/login.qtpl:3
	return qs422016
//line pages/account/login/login.qtpl:3
}

//line pages/account/login/login.qtpl:5
func (p *Page) StreamContent(qw422016 *qt422016.Writer) {
//line pages/account/login/login.qtpl:7
}

//line pages/account/login/login.qtpl:7
func (p *Page) WriteContent(qq422016 qtio422016.Writer) {
//line pages/account/login/login.qtpl:7
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/account/login/login.qtpl:7
	p.StreamContent(qw422016)
//line pages/account/login/login.qtpl:7
	qt422016.ReleaseWriter(qw422016)
//line pages/account/login/login.qtpl:7
}

//line pages/account/login/login.qtpl:7
func (p *Page) Content() string {
//line pages/account/login/login.qtpl:7
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/account/login/login.qtpl:7
	p.WriteContent(qb422016)
//line pages/account/login/login.qtpl:7
	qs422016 := string(qb422016.B)
//line pages/account/login/login.qtpl:7
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/account/login/login.qtpl:7
	return qs422016
//line pages/account/login/login.qtpl:7
}

//line pages/account/login/login.qtpl:9
func (p *Page) StreamJavascripts(qw422016 *qt422016.Writer) {
//line pages/account/login/login.qtpl:9
	qw422016.N().S(`<script src="/j/form.js"></script>`)
//line pages/account/login/login.qtpl:9
}

//line pages/account/login/login.qtpl:9
func (p *Page) WriteJavascripts(qq422016 qtio422016.Writer) {
//line pages/account/login/login.qtpl:9
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/account/login/login.qtpl:9
	p.StreamJavascripts(qw422016)
//line pages/account/login/login.qtpl:9
	qt422016.ReleaseWriter(qw422016)
//line pages/account/login/login.qtpl:9
}

//line pages/account/login/login.qtpl:9
func (p *Page) Javascripts() string {
//line pages/account/login/login.qtpl:9
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/account/login/login.qtpl:9
	p.WriteJavascripts(qb422016)
//line pages/account/login/login.qtpl:9
	qs422016 := string(qb422016.B)
//line pages/account/login/login.qtpl:9
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/account/login/login.qtpl:9
	return qs422016
//line pages/account/login/login.qtpl:9
}
