// Code generated by qtc from "view.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line pages/admin/site/view/view.qtpl:1
package view

//line pages/admin/site/view/view.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line pages/admin/site/view/view.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line pages/admin/site/view/view.qtpl:1
func (p *Page) StreamTitle(qw422016 *qt422016.Writer) {
//line pages/admin/site/view/view.qtpl:1
	qw422016.E().S(p.TranslatePlural("site"))
//line pages/admin/site/view/view.qtpl:1
	qw422016.N().S(` > `)
//line pages/admin/site/view/view.qtpl:1
	qw422016.E().S(p.translatedName)
//line pages/admin/site/view/view.qtpl:1
}

//line pages/admin/site/view/view.qtpl:1
func (p *Page) WriteTitle(qq422016 qtio422016.Writer) {
//line pages/admin/site/view/view.qtpl:1
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/admin/site/view/view.qtpl:1
	p.StreamTitle(qw422016)
//line pages/admin/site/view/view.qtpl:1
	qt422016.ReleaseWriter(qw422016)
//line pages/admin/site/view/view.qtpl:1
}

//line pages/admin/site/view/view.qtpl:1
func (p *Page) Title() string {
//line pages/admin/site/view/view.qtpl:1
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/admin/site/view/view.qtpl:1
	p.WriteTitle(qb422016)
//line pages/admin/site/view/view.qtpl:1
	qs422016 := string(qb422016.B)
//line pages/admin/site/view/view.qtpl:1
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/admin/site/view/view.qtpl:1
	return qs422016
//line pages/admin/site/view/view.qtpl:1
}

//line pages/admin/site/view/view.qtpl:3
func (p *Page) StreamContent(qw422016 *qt422016.Writer) {
//line pages/admin/site/view/view.qtpl:3
	qw422016.N().S(`<main class="content"><h1>`)
//line pages/admin/site/view/view.qtpl:5
	qw422016.E().S(p.TranslatePlural("site"))
//line pages/admin/site/view/view.qtpl:5
	qw422016.E().S(" > ")
//line pages/admin/site/view/view.qtpl:5
	qw422016.E().S(p.translatedName)
//line pages/admin/site/view/view.qtpl:5
	qw422016.N().S(`</h1><p><a href="`)
//line pages/admin/site/view/view.qtpl:8
	qw422016.E().S(p.AdminURL())
//line pages/admin/site/view/view.qtpl:8
	qw422016.N().S(`/Site">`)
//line pages/admin/site/view/view.qtpl:8
	qw422016.E().S(p.Translate("backToOverview"))
//line pages/admin/site/view/view.qtpl:8
	qw422016.N().S(`</a><br><a href="`)
//line pages/admin/site/view/view.qtpl:9
	qw422016.E().S(p.AdminURL())
//line pages/admin/site/view/view.qtpl:9
	qw422016.N().S(`/Site/Update?id=`)
//line pages/admin/site/view/view.qtpl:9
	qw422016.E().S(p.site.ID())
//line pages/admin/site/view/view.qtpl:9
	qw422016.N().S(`">`)
//line pages/admin/site/view/view.qtpl:9
	qw422016.E().S("✎ ")
//line pages/admin/site/view/view.qtpl:9
	qw422016.E().S(p.Translate("update"))
//line pages/admin/site/view/view.qtpl:9
	qw422016.N().S(`</a></p><p>`)
//line pages/admin/site/view/view.qtpl:11
	if p.site.Online() {
//line pages/admin/site/view/view.qtpl:11
		qw422016.E().S(p.Translate("yes_"))
//line pages/admin/site/view/view.qtpl:11
	} else {
//line pages/admin/site/view/view.qtpl:11
		qw422016.E().S(p.Translate("no_"))
//line pages/admin/site/view/view.qtpl:11
	}
//line pages/admin/site/view/view.qtpl:11
	qw422016.N().S(`</p><p>`)
//line pages/admin/site/view/view.qtpl:12
	qw422016.E().S(p.Translate("language") + ": ")
//line pages/admin/site/view/view.qtpl:12
	if p.siteLanguage != nil {
//line pages/admin/site/view/view.qtpl:12
		qw422016.E().S(p.siteLanguage.Translate(p.language.ID()))
//line pages/admin/site/view/view.qtpl:12
	}
//line pages/admin/site/view/view.qtpl:12
	qw422016.N().S(`</p><p>`)
//line pages/admin/site/view/view.qtpl:13
	qw422016.E().S(p.Translate("country") + ": ")
//line pages/admin/site/view/view.qtpl:13
	if p.siteCountry != nil {
//line pages/admin/site/view/view.qtpl:13
		qw422016.E().S(p.siteCountry.Translate(p.language.ID()))
//line pages/admin/site/view/view.qtpl:13
	}
//line pages/admin/site/view/view.qtpl:13
	qw422016.N().S(`</p><p>`)
//line pages/admin/site/view/view.qtpl:15
	qw422016.E().S(p.TranslatePlural("currency") + ": ")
//line pages/admin/site/view/view.qtpl:15
	qw422016.N().S(`<ul>`)
//line pages/admin/site/view/view.qtpl:17
	for k := range p.currencies {
//line pages/admin/site/view/view.qtpl:17
		qw422016.N().S(`<li>`)
//line pages/admin/site/view/view.qtpl:18
		qw422016.E().S(p.currencies[k])
//line pages/admin/site/view/view.qtpl:18
		qw422016.N().S(`</li>`)
//line pages/admin/site/view/view.qtpl:19
	}
//line pages/admin/site/view/view.qtpl:19
	qw422016.N().S(`</ul></p></main>`)
//line pages/admin/site/view/view.qtpl:23
}

//line pages/admin/site/view/view.qtpl:23
func (p *Page) WriteContent(qq422016 qtio422016.Writer) {
//line pages/admin/site/view/view.qtpl:23
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/admin/site/view/view.qtpl:23
	p.StreamContent(qw422016)
//line pages/admin/site/view/view.qtpl:23
	qt422016.ReleaseWriter(qw422016)
//line pages/admin/site/view/view.qtpl:23
}

//line pages/admin/site/view/view.qtpl:23
func (p *Page) Content() string {
//line pages/admin/site/view/view.qtpl:23
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/admin/site/view/view.qtpl:23
	p.WriteContent(qb422016)
//line pages/admin/site/view/view.qtpl:23
	qs422016 := string(qb422016.B)
//line pages/admin/site/view/view.qtpl:23
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/admin/site/view/view.qtpl:23
	return qs422016
//line pages/admin/site/view/view.qtpl:23
}
