// Code generated by qtc from "view.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line pages/admin/user/group/view/view.qtpl:1
package view

//line pages/admin/user/group/view/view.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line pages/admin/user/group/view/view.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line pages/admin/user/group/view/view.qtpl:1
func (p *Page) StreamTitle(qw422016 *qt422016.Writer) {
//line pages/admin/user/group/view/view.qtpl:1
	qw422016.E().S(p.Translate("userGroup"))
//line pages/admin/user/group/view/view.qtpl:1
}

//line pages/admin/user/group/view/view.qtpl:1
func (p *Page) WriteTitle(qq422016 qtio422016.Writer) {
//line pages/admin/user/group/view/view.qtpl:1
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/admin/user/group/view/view.qtpl:1
	p.StreamTitle(qw422016)
//line pages/admin/user/group/view/view.qtpl:1
	qt422016.ReleaseWriter(qw422016)
//line pages/admin/user/group/view/view.qtpl:1
}

//line pages/admin/user/group/view/view.qtpl:1
func (p *Page) Title() string {
//line pages/admin/user/group/view/view.qtpl:1
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/admin/user/group/view/view.qtpl:1
	p.WriteTitle(qb422016)
//line pages/admin/user/group/view/view.qtpl:1
	qs422016 := string(qb422016.B)
//line pages/admin/user/group/view/view.qtpl:1
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/admin/user/group/view/view.qtpl:1
	return qs422016
//line pages/admin/user/group/view/view.qtpl:1
}

//line pages/admin/user/group/view/view.qtpl:3
func (p *Page) StreamContent(qw422016 *qt422016.Writer) {
//line pages/admin/user/group/view/view.qtpl:3
	qw422016.N().S(`<main class="content"><h1>`)
//line pages/admin/user/group/view/view.qtpl:5
	qw422016.E().S(p.Translate("userGroup"))
//line pages/admin/user/group/view/view.qtpl:5
	qw422016.N().S(`</h1></main>`)
//line pages/admin/user/group/view/view.qtpl:7
}

//line pages/admin/user/group/view/view.qtpl:7
func (p *Page) WriteContent(qq422016 qtio422016.Writer) {
//line pages/admin/user/group/view/view.qtpl:7
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/admin/user/group/view/view.qtpl:7
	p.StreamContent(qw422016)
//line pages/admin/user/group/view/view.qtpl:7
	qt422016.ReleaseWriter(qw422016)
//line pages/admin/user/group/view/view.qtpl:7
}

//line pages/admin/user/group/view/view.qtpl:7
func (p *Page) Content() string {
//line pages/admin/user/group/view/view.qtpl:7
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/admin/user/group/view/view.qtpl:7
	p.WriteContent(qb422016)
//line pages/admin/user/group/view/view.qtpl:7
	qs422016 := string(qb422016.B)
//line pages/admin/user/group/view/view.qtpl:7
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/admin/user/group/view/view.qtpl:7
	return qs422016
//line pages/admin/user/group/view/view.qtpl:7
}
