// Code generated by qtc from "spa.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line pages/spa/spa.qtpl:1
package spa

//line pages/spa/spa.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line pages/spa/spa.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line pages/spa/spa.qtpl:1
func (p *Page) StreamTitle(qw422016 *qt422016.Writer) {
//line pages/spa/spa.qtpl:1
	qw422016.E().S("THIS IS SPA")
//line pages/spa/spa.qtpl:1
}

//line pages/spa/spa.qtpl:1
func (p *Page) WriteTitle(qq422016 qtio422016.Writer) {
//line pages/spa/spa.qtpl:1
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/spa/spa.qtpl:1
	p.StreamTitle(qw422016)
//line pages/spa/spa.qtpl:1
	qt422016.ReleaseWriter(qw422016)
//line pages/spa/spa.qtpl:1
}

//line pages/spa/spa.qtpl:1
func (p *Page) Title() string {
//line pages/spa/spa.qtpl:1
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/spa/spa.qtpl:1
	p.WriteTitle(qb422016)
//line pages/spa/spa.qtpl:1
	qs422016 := string(qb422016.B)
//line pages/spa/spa.qtpl:1
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/spa/spa.qtpl:1
	return qs422016
//line pages/spa/spa.qtpl:1
}

//line pages/spa/spa.qtpl:3
func (p *Page) StreamContent(qw422016 *qt422016.Writer) {
//line pages/spa/spa.qtpl:3
	qw422016.N().S(`<div id="app"></div>`)
//line pages/spa/spa.qtpl:5
}

//line pages/spa/spa.qtpl:5
func (p *Page) WriteContent(qq422016 qtio422016.Writer) {
//line pages/spa/spa.qtpl:5
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/spa/spa.qtpl:5
	p.StreamContent(qw422016)
//line pages/spa/spa.qtpl:5
	qt422016.ReleaseWriter(qw422016)
//line pages/spa/spa.qtpl:5
}

//line pages/spa/spa.qtpl:5
func (p *Page) Content() string {
//line pages/spa/spa.qtpl:5
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/spa/spa.qtpl:5
	p.WriteContent(qb422016)
//line pages/spa/spa.qtpl:5
	qs422016 := string(qb422016.B)
//line pages/spa/spa.qtpl:5
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/spa/spa.qtpl:5
	return qs422016
//line pages/spa/spa.qtpl:5
}

//line pages/spa/spa.qtpl:7
func (p *Page) StreamJavascripts(qw422016 *qt422016.Writer) {
//line pages/spa/spa.qtpl:7
	qw422016.N().S(`<script src="/j/spa/main.js"></script>`)
//line pages/spa/spa.qtpl:7
}

//line pages/spa/spa.qtpl:7
func (p *Page) WriteJavascripts(qq422016 qtio422016.Writer) {
//line pages/spa/spa.qtpl:7
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/spa/spa.qtpl:7
	p.StreamJavascripts(qw422016)
//line pages/spa/spa.qtpl:7
	qt422016.ReleaseWriter(qw422016)
//line pages/spa/spa.qtpl:7
}

//line pages/spa/spa.qtpl:7
func (p *Page) Javascripts() string {
//line pages/spa/spa.qtpl:7
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/spa/spa.qtpl:7
	p.WriteJavascripts(qb422016)
//line pages/spa/spa.qtpl:7
	qs422016 := string(qb422016.B)
//line pages/spa/spa.qtpl:7
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/spa/spa.qtpl:7
	return qs422016
//line pages/spa/spa.qtpl:7
}
