// Code generated by qtc from "catalog.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line pages/catalog/catalog.qtpl:1
package catalog

//line pages/catalog/catalog.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line pages/catalog/catalog.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line pages/catalog/catalog.qtpl:1
func (p *Page) StreamStylesheets(qw422016 *qt422016.Writer) {
//line pages/catalog/catalog.qtpl:1
	qw422016.N().S(`<link rel="stylesheet" href="/c/catalog.css">`)
//line pages/catalog/catalog.qtpl:1
}

//line pages/catalog/catalog.qtpl:1
func (p *Page) WriteStylesheets(qq422016 qtio422016.Writer) {
//line pages/catalog/catalog.qtpl:1
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/catalog/catalog.qtpl:1
	p.StreamStylesheets(qw422016)
//line pages/catalog/catalog.qtpl:1
	qt422016.ReleaseWriter(qw422016)
//line pages/catalog/catalog.qtpl:1
}

//line pages/catalog/catalog.qtpl:1
func (p *Page) Stylesheets() string {
//line pages/catalog/catalog.qtpl:1
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/catalog/catalog.qtpl:1
	p.WriteStylesheets(qb422016)
//line pages/catalog/catalog.qtpl:1
	qs422016 := string(qb422016.B)
//line pages/catalog/catalog.qtpl:1
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/catalog/catalog.qtpl:1
	return qs422016
//line pages/catalog/catalog.qtpl:1
}

//line pages/catalog/catalog.qtpl:3
func (p *Page) StreamTitle(qw422016 *qt422016.Writer) {
//line pages/catalog/catalog.qtpl:3
	qw422016.E().S(p.Translate("catalog"))
//line pages/catalog/catalog.qtpl:3
}

//line pages/catalog/catalog.qtpl:3
func (p *Page) WriteTitle(qq422016 qtio422016.Writer) {
//line pages/catalog/catalog.qtpl:3
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/catalog/catalog.qtpl:3
	p.StreamTitle(qw422016)
//line pages/catalog/catalog.qtpl:3
	qt422016.ReleaseWriter(qw422016)
//line pages/catalog/catalog.qtpl:3
}

//line pages/catalog/catalog.qtpl:3
func (p *Page) Title() string {
//line pages/catalog/catalog.qtpl:3
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/catalog/catalog.qtpl:3
	p.WriteTitle(qb422016)
//line pages/catalog/catalog.qtpl:3
	qs422016 := string(qb422016.B)
//line pages/catalog/catalog.qtpl:3
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/catalog/catalog.qtpl:3
	return qs422016
//line pages/catalog/catalog.qtpl:3
}

//line pages/catalog/catalog.qtpl:5
func (p *Page) StreamContent(qw422016 *qt422016.Writer) {
//line pages/catalog/catalog.qtpl:5
	qw422016.N().S(`<div class="catalog"><div class="filters"></div><h1>`)
//line pages/catalog/catalog.qtpl:8
	qw422016.E().S(p.Translate("catalog"))
//line pages/catalog/catalog.qtpl:8
	qw422016.N().S(`</h1></div>`)
//line pages/catalog/catalog.qtpl:10
}

//line pages/catalog/catalog.qtpl:10
func (p *Page) WriteContent(qq422016 qtio422016.Writer) {
//line pages/catalog/catalog.qtpl:10
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/catalog/catalog.qtpl:10
	p.StreamContent(qw422016)
//line pages/catalog/catalog.qtpl:10
	qt422016.ReleaseWriter(qw422016)
//line pages/catalog/catalog.qtpl:10
}

//line pages/catalog/catalog.qtpl:10
func (p *Page) Content() string {
//line pages/catalog/catalog.qtpl:10
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/catalog/catalog.qtpl:10
	p.WriteContent(qb422016)
//line pages/catalog/catalog.qtpl:10
	qs422016 := string(qb422016.B)
//line pages/catalog/catalog.qtpl:10
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/catalog/catalog.qtpl:10
	return qs422016
//line pages/catalog/catalog.qtpl:10
}
