// Code generated by qtc from "overview.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line pages/admin/site/overview/overview.qtpl:1
package overview

//line pages/admin/site/overview/overview.qtpl:1
import "time"

//line pages/admin/site/overview/overview.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line pages/admin/site/overview/overview.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line pages/admin/site/overview/overview.qtpl:3
func (p *Page) StreamTitle(qw422016 *qt422016.Writer) {
//line pages/admin/site/overview/overview.qtpl:3
	qw422016.E().S(p.TranslatePlural("site"))
//line pages/admin/site/overview/overview.qtpl:3
}

//line pages/admin/site/overview/overview.qtpl:3
func (p *Page) WriteTitle(qq422016 qtio422016.Writer) {
//line pages/admin/site/overview/overview.qtpl:3
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/admin/site/overview/overview.qtpl:3
	p.StreamTitle(qw422016)
//line pages/admin/site/overview/overview.qtpl:3
	qt422016.ReleaseWriter(qw422016)
//line pages/admin/site/overview/overview.qtpl:3
}

//line pages/admin/site/overview/overview.qtpl:3
func (p *Page) Title() string {
//line pages/admin/site/overview/overview.qtpl:3
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/admin/site/overview/overview.qtpl:3
	p.WriteTitle(qb422016)
//line pages/admin/site/overview/overview.qtpl:3
	qs422016 := string(qb422016.B)
//line pages/admin/site/overview/overview.qtpl:3
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/admin/site/overview/overview.qtpl:3
	return qs422016
//line pages/admin/site/overview/overview.qtpl:3
}

//line pages/admin/site/overview/overview.qtpl:5
func (p *Page) StreamContent(qw422016 *qt422016.Writer) {
//line pages/admin/site/overview/overview.qtpl:5
	qw422016.N().S(`<main class="content"><h1>`)
//line pages/admin/site/overview/overview.qtpl:7
	qw422016.E().S(p.TranslatePlural("site"))
//line pages/admin/site/overview/overview.qtpl:7
	qw422016.N().S(`</h1>`)
//line pages/admin/site/overview/overview.qtpl:8
	qw422016.N().S(p.actions.RenderOverviewActions())
//line pages/admin/site/overview/overview.qtpl:9
	qw422016.N().S(p.filter.RenderOverviewFilter(p.GetCoreContext()))
//line pages/admin/site/overview/overview.qtpl:10
	if len(p.sites) > 0 {
//line pages/admin/site/overview/overview.qtpl:10
		qw422016.N().S(`<table><thead><tr>`)
//line pages/admin/site/overview/overview.qtpl:14
		if p.canUpdate || p.canDelete {
//line pages/admin/site/overview/overview.qtpl:14
			qw422016.N().S(`<th><input type="checkbox" name="check"></th><th></th>`)
//line pages/admin/site/overview/overview.qtpl:17
		}
//line pages/admin/site/overview/overview.qtpl:17
		qw422016.N().S(`<th></th>`)
//line pages/admin/site/overview/overview.qtpl:19
		qw422016.N().S(p.filter.RenderOverviewColumnTableHeaders(p.GetCoreContext()))
//line pages/admin/site/overview/overview.qtpl:19
		qw422016.N().S(`</tr></thead><tbody>`)
//line pages/admin/site/overview/overview.qtpl:23
		for k := range p.sites {
//line pages/admin/site/overview/overview.qtpl:23
			qw422016.N().S(`<tr>`)
//line pages/admin/site/overview/overview.qtpl:25
			if p.canUpdate || p.canDelete {
//line pages/admin/site/overview/overview.qtpl:25
				qw422016.N().S(`<td><input type="checkbox" name="check" data-id="`)
//line pages/admin/site/overview/overview.qtpl:26
				qw422016.E().S(p.sites[k].ID())
//line pages/admin/site/overview/overview.qtpl:26
				qw422016.N().S(`"></td><td><a href="`)
//line pages/admin/site/overview/overview.qtpl:27
				qw422016.E().S(p.AdminURL())
//line pages/admin/site/overview/overview.qtpl:27
				qw422016.N().S(`/Site/Update?id=`)
//line pages/admin/site/overview/overview.qtpl:27
				qw422016.E().S(p.sites[k].ID())
//line pages/admin/site/overview/overview.qtpl:27
				qw422016.N().S(`">✎</a></td>`)
//line pages/admin/site/overview/overview.qtpl:28
			}
//line pages/admin/site/overview/overview.qtpl:28
			qw422016.N().S(`<td><a href="`)
//line pages/admin/site/overview/overview.qtpl:30
			qw422016.E().S(p.AdminURL())
//line pages/admin/site/overview/overview.qtpl:30
			qw422016.N().S(`/Site/View?id=`)
//line pages/admin/site/overview/overview.qtpl:30
			qw422016.E().S(p.sites[k].ID())
//line pages/admin/site/overview/overview.qtpl:30
			qw422016.N().S(`">`)
//line pages/admin/site/overview/overview.qtpl:30
			qw422016.E().S(p.TranslatePlural("detail"))
//line pages/admin/site/overview/overview.qtpl:30
			qw422016.N().S(`</a></td>`)
//line pages/admin/site/overview/overview.qtpl:32
			for key := range p.filter.ColumnsInOrder() {
//line pages/admin/site/overview/overview.qtpl:32
				qw422016.N().S(`<td>`)
//line pages/admin/site/overview/overview.qtpl:34
				switch key {
//line pages/admin/site/overview/overview.qtpl:35
				case 0:
//line pages/admin/site/overview/overview.qtpl:36
					qw422016.E().S(p.sites[k].ID())
//line pages/admin/site/overview/overview.qtpl:37
				case 1:
//line pages/admin/site/overview/overview.qtpl:38
					if p.sites[k].Online() {
//line pages/admin/site/overview/overview.qtpl:38
						qw422016.E().S(p.Translate("yes_"))
//line pages/admin/site/overview/overview.qtpl:38
					} else {
//line pages/admin/site/overview/overview.qtpl:38
						qw422016.E().S(p.Translate("no_"))
//line pages/admin/site/overview/overview.qtpl:38
					}
//line pages/admin/site/overview/overview.qtpl:39
				case 2:
//line pages/admin/site/overview/overview.qtpl:39
					qw422016.N().S(`<a href="`)
//line pages/admin/site/overview/overview.qtpl:40
					qw422016.E().S(p.AdminURL())
//line pages/admin/site/overview/overview.qtpl:40
					qw422016.N().S(`/User/View?id=`)
//line pages/admin/site/overview/overview.qtpl:40
					qw422016.E().S(p.sites[k].CreatedByID())
//line pages/admin/site/overview/overview.qtpl:40
					qw422016.N().S(`">`)
//line pages/admin/site/overview/overview.qtpl:41
					qw422016.E().S(p.rendererService.CreatedBy(p.sites[k], p.language.ID()))
//line pages/admin/site/overview/overview.qtpl:41
					qw422016.N().S(`</a>`)
//line pages/admin/site/overview/overview.qtpl:43
				case 3:
//line pages/admin/site/overview/overview.qtpl:44
					qw422016.E().S(p.sites[k].CreatedAt().Format(time.RFC3339[0:9]))
//line pages/admin/site/overview/overview.qtpl:45
				case 4:
//line pages/admin/site/overview/overview.qtpl:46
					if p.sites[k].IsUpdated() {
//line pages/admin/site/overview/overview.qtpl:46
						qw422016.N().S(`<a href="`)
//line pages/admin/site/overview/overview.qtpl:47
						qw422016.E().S(p.AdminURL())
//line pages/admin/site/overview/overview.qtpl:47
						qw422016.N().S(`/User/View?id=`)
//line pages/admin/site/overview/overview.qtpl:47
						qw422016.E().S(*p.sites[k].UpdatedByID())
//line pages/admin/site/overview/overview.qtpl:47
						qw422016.N().S(`">`)
//line pages/admin/site/overview/overview.qtpl:48
						qw422016.E().S(p.rendererService.UpdatedBy(p.sites[k], p.language.ID()))
//line pages/admin/site/overview/overview.qtpl:48
						qw422016.N().S(`</a>`)
//line pages/admin/site/overview/overview.qtpl:50
					}
//line pages/admin/site/overview/overview.qtpl:51
				case 5:
//line pages/admin/site/overview/overview.qtpl:52
					if p.sites[k].UpdatedAt() != nil {
//line pages/admin/site/overview/overview.qtpl:52
						qw422016.E().S(p.sites[k].UpdatedAt().Format(time.RFC3339[0:9]))
//line pages/admin/site/overview/overview.qtpl:52
					}
//line pages/admin/site/overview/overview.qtpl:53
				case 6:
//line pages/admin/site/overview/overview.qtpl:54
					if p.sites[k].LocalizedName() != nil {
//line pages/admin/site/overview/overview.qtpl:54
						qw422016.E().S(*p.sites[k].LocalizedName())
//line pages/admin/site/overview/overview.qtpl:54
					}
//line pages/admin/site/overview/overview.qtpl:55
				case 7:
//line pages/admin/site/overview/overview.qtpl:56
					if p.sites[k].Language() != nil {
//line pages/admin/site/overview/overview.qtpl:57
						qw422016.E().S(p.rendererService.LanguageName(*p.sites[k].Language(), p.language.ID()))
//line pages/admin/site/overview/overview.qtpl:58
					}
//line pages/admin/site/overview/overview.qtpl:59
				case 8:
//line pages/admin/site/overview/overview.qtpl:60
					if p.sites[k].Country() != nil {
//line pages/admin/site/overview/overview.qtpl:61
						qw422016.E().S(p.rendererService.CountryName(*p.sites[k].Country(), p.language.ID()))
//line pages/admin/site/overview/overview.qtpl:62
					}
//line pages/admin/site/overview/overview.qtpl:63
				case 9:
//line pages/admin/site/overview/overview.qtpl:64
					qw422016.E().V(p.sites[k].CurrenciesCount())
//line pages/admin/site/overview/overview.qtpl:65
				}
//line pages/admin/site/overview/overview.qtpl:65
				qw422016.N().S(`</td>`)
//line pages/admin/site/overview/overview.qtpl:67
			}
//line pages/admin/site/overview/overview.qtpl:67
			qw422016.N().S(`</tr>`)
//line pages/admin/site/overview/overview.qtpl:69
		}
//line pages/admin/site/overview/overview.qtpl:69
		qw422016.N().S(`</tbody></table>`)
//line pages/admin/site/overview/overview.qtpl:72
	} else {
//line pages/admin/site/overview/overview.qtpl:73
		qw422016.E().S(p.Translate("noResultsFound"))
//line pages/admin/site/overview/overview.qtpl:74
	}
//line pages/admin/site/overview/overview.qtpl:74
	qw422016.N().S(`</main>`)
//line pages/admin/site/overview/overview.qtpl:76
}

//line pages/admin/site/overview/overview.qtpl:76
func (p *Page) WriteContent(qq422016 qtio422016.Writer) {
//line pages/admin/site/overview/overview.qtpl:76
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/admin/site/overview/overview.qtpl:76
	p.StreamContent(qw422016)
//line pages/admin/site/overview/overview.qtpl:76
	qt422016.ReleaseWriter(qw422016)
//line pages/admin/site/overview/overview.qtpl:76
}

//line pages/admin/site/overview/overview.qtpl:76
func (p *Page) Content() string {
//line pages/admin/site/overview/overview.qtpl:76
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/admin/site/overview/overview.qtpl:76
	p.WriteContent(qb422016)
//line pages/admin/site/overview/overview.qtpl:76
	qs422016 := string(qb422016.B)
//line pages/admin/site/overview/overview.qtpl:76
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/admin/site/overview/overview.qtpl:76
	return qs422016
//line pages/admin/site/overview/overview.qtpl:76
}

//line pages/admin/site/overview/overview.qtpl:78
func (p *Page) StreamStylesheets(qw422016 *qt422016.Writer) {
//line pages/admin/site/overview/overview.qtpl:79
	if p.filter.ShouldShowSearch() {
//line pages/admin/site/overview/overview.qtpl:79
		qw422016.N().S(`<link rel="stylesheet" href="/c/a/f.css">`)
//line pages/admin/site/overview/overview.qtpl:81
	}
//line pages/admin/site/overview/overview.qtpl:82
}

//line pages/admin/site/overview/overview.qtpl:82
func (p *Page) WriteStylesheets(qq422016 qtio422016.Writer) {
//line pages/admin/site/overview/overview.qtpl:82
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/admin/site/overview/overview.qtpl:82
	p.StreamStylesheets(qw422016)
//line pages/admin/site/overview/overview.qtpl:82
	qt422016.ReleaseWriter(qw422016)
//line pages/admin/site/overview/overview.qtpl:82
}

//line pages/admin/site/overview/overview.qtpl:82
func (p *Page) Stylesheets() string {
//line pages/admin/site/overview/overview.qtpl:82
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/admin/site/overview/overview.qtpl:82
	p.WriteStylesheets(qb422016)
//line pages/admin/site/overview/overview.qtpl:82
	qs422016 := string(qb422016.B)
//line pages/admin/site/overview/overview.qtpl:82
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/admin/site/overview/overview.qtpl:82
	return qs422016
//line pages/admin/site/overview/overview.qtpl:82
}

//line pages/admin/site/overview/overview.qtpl:84
func (p *Page) StreamJavascripts(qw422016 *qt422016.Writer) {
//line pages/admin/site/overview/overview.qtpl:85
	if p.filter.ShouldShowSearch() {
//line pages/admin/site/overview/overview.qtpl:85
		qw422016.N().S(`<script src="/j/a/f.js"></script>`)
//line pages/admin/site/overview/overview.qtpl:87
	}
//line pages/admin/site/overview/overview.qtpl:88
	if len(p.sites) > 0 {
//line pages/admin/site/overview/overview.qtpl:88
		qw422016.N().S(`<script src="/j/a/o.js"></script>`)
//line pages/admin/site/overview/overview.qtpl:90
		qw422016.N().S(p.rendererService.DefaultOverviewTranslations(p.GetCoreContext()))
//line pages/admin/site/overview/overview.qtpl:91
	}
//line pages/admin/site/overview/overview.qtpl:92
}

//line pages/admin/site/overview/overview.qtpl:92
func (p *Page) WriteJavascripts(qq422016 qtio422016.Writer) {
//line pages/admin/site/overview/overview.qtpl:92
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/admin/site/overview/overview.qtpl:92
	p.StreamJavascripts(qw422016)
//line pages/admin/site/overview/overview.qtpl:92
	qt422016.ReleaseWriter(qw422016)
//line pages/admin/site/overview/overview.qtpl:92
}

//line pages/admin/site/overview/overview.qtpl:92
func (p *Page) Javascripts() string {
//line pages/admin/site/overview/overview.qtpl:92
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/admin/site/overview/overview.qtpl:92
	p.WriteJavascripts(qb422016)
//line pages/admin/site/overview/overview.qtpl:92
	qs422016 := string(qb422016.B)
//line pages/admin/site/overview/overview.qtpl:92
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/admin/site/overview/overview.qtpl:92
	return qs422016
//line pages/admin/site/overview/overview.qtpl:92
}
