// Code generated by qtc from "overview.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line pages/account/overview/overview.qtpl:1
package overview

//line pages/account/overview/overview.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line pages/account/overview/overview.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line pages/account/overview/overview.qtpl:1
func (p *Page) StreamTitle(qw422016 *qt422016.Writer) {
//line pages/account/overview/overview.qtpl:1
	qw422016.E().S(p.Translate("account"))
//line pages/account/overview/overview.qtpl:1
	qw422016.N().S(` `)
//line pages/account/overview/overview.qtpl:1
	qw422016.E().S(p.Translate("information"))
//line pages/account/overview/overview.qtpl:1
}

//line pages/account/overview/overview.qtpl:1
func (p *Page) WriteTitle(qq422016 qtio422016.Writer) {
//line pages/account/overview/overview.qtpl:1
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/account/overview/overview.qtpl:1
	p.StreamTitle(qw422016)
//line pages/account/overview/overview.qtpl:1
	qt422016.ReleaseWriter(qw422016)
//line pages/account/overview/overview.qtpl:1
}

//line pages/account/overview/overview.qtpl:1
func (p *Page) Title() string {
//line pages/account/overview/overview.qtpl:1
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/account/overview/overview.qtpl:1
	p.WriteTitle(qb422016)
//line pages/account/overview/overview.qtpl:1
	qs422016 := string(qb422016.B)
//line pages/account/overview/overview.qtpl:1
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/account/overview/overview.qtpl:1
	return qs422016
//line pages/account/overview/overview.qtpl:1
}

//line pages/account/overview/overview.qtpl:3
func (p *Page) StreamContent(qw422016 *qt422016.Writer) {
//line pages/account/overview/overview.qtpl:5
}

//line pages/account/overview/overview.qtpl:5
func (p *Page) WriteContent(qq422016 qtio422016.Writer) {
//line pages/account/overview/overview.qtpl:5
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/account/overview/overview.qtpl:5
	p.StreamContent(qw422016)
//line pages/account/overview/overview.qtpl:5
	qt422016.ReleaseWriter(qw422016)
//line pages/account/overview/overview.qtpl:5
}

//line pages/account/overview/overview.qtpl:5
func (p *Page) Content() string {
//line pages/account/overview/overview.qtpl:5
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/account/overview/overview.qtpl:5
	p.WriteContent(qb422016)
//line pages/account/overview/overview.qtpl:5
	qs422016 := string(qb422016.B)
//line pages/account/overview/overview.qtpl:5
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/account/overview/overview.qtpl:5
	return qs422016
//line pages/account/overview/overview.qtpl:5
}

//line pages/account/overview/overview.qtpl:7
func (p *Page) StreamStylesheets(qw422016 *qt422016.Writer) {
//line pages/account/overview/overview.qtpl:7
	qw422016.N().S(`<link rel="stylesheet" href="/c/account.css">`)
//line pages/account/overview/overview.qtpl:7
}

//line pages/account/overview/overview.qtpl:7
func (p *Page) WriteStylesheets(qq422016 qtio422016.Writer) {
//line pages/account/overview/overview.qtpl:7
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/account/overview/overview.qtpl:7
	p.StreamStylesheets(qw422016)
//line pages/account/overview/overview.qtpl:7
	qt422016.ReleaseWriter(qw422016)
//line pages/account/overview/overview.qtpl:7
}

//line pages/account/overview/overview.qtpl:7
func (p *Page) Stylesheets() string {
//line pages/account/overview/overview.qtpl:7
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/account/overview/overview.qtpl:7
	p.WriteStylesheets(qb422016)
//line pages/account/overview/overview.qtpl:7
	qs422016 := string(qb422016.B)
//line pages/account/overview/overview.qtpl:7
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/account/overview/overview.qtpl:7
	return qs422016
//line pages/account/overview/overview.qtpl:7
}
