// Code generated by qtc from "overview.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line pages/admin/user/group/overview/overview.qtpl:1
package overview

//line pages/admin/user/group/overview/overview.qtpl:1
import "time"

//line pages/admin/user/group/overview/overview.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line pages/admin/user/group/overview/overview.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line pages/admin/user/group/overview/overview.qtpl:3
func (p *Page) StreamTitle(qw422016 *qt422016.Writer) {
//line pages/admin/user/group/overview/overview.qtpl:3
	qw422016.E().S(p.TranslatePlural("userGroup"))
//line pages/admin/user/group/overview/overview.qtpl:3
}

//line pages/admin/user/group/overview/overview.qtpl:3
func (p *Page) WriteTitle(qq422016 qtio422016.Writer) {
//line pages/admin/user/group/overview/overview.qtpl:3
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/admin/user/group/overview/overview.qtpl:3
	p.StreamTitle(qw422016)
//line pages/admin/user/group/overview/overview.qtpl:3
	qt422016.ReleaseWriter(qw422016)
//line pages/admin/user/group/overview/overview.qtpl:3
}

//line pages/admin/user/group/overview/overview.qtpl:3
func (p *Page) Title() string {
//line pages/admin/user/group/overview/overview.qtpl:3
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/admin/user/group/overview/overview.qtpl:3
	p.WriteTitle(qb422016)
//line pages/admin/user/group/overview/overview.qtpl:3
	qs422016 := string(qb422016.B)
//line pages/admin/user/group/overview/overview.qtpl:3
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/admin/user/group/overview/overview.qtpl:3
	return qs422016
//line pages/admin/user/group/overview/overview.qtpl:3
}

//line pages/admin/user/group/overview/overview.qtpl:5
func (p *Page) StreamContent(qw422016 *qt422016.Writer) {
//line pages/admin/user/group/overview/overview.qtpl:5
	qw422016.N().S(`<main class="content"><h1>`)
//line pages/admin/user/group/overview/overview.qtpl:7
	qw422016.E().S(p.TranslatePlural("userGroup"))
//line pages/admin/user/group/overview/overview.qtpl:7
	qw422016.N().S(`</h1>`)
//line pages/admin/user/group/overview/overview.qtpl:8
	qw422016.N().S(p.actions.RenderOverviewActions())
//line pages/admin/user/group/overview/overview.qtpl:9
	qw422016.N().S(p.filter.RenderOverviewFilter(p.GetCoreContext()))
//line pages/admin/user/group/overview/overview.qtpl:10
	if len(p.userGroups) > 0 {
//line pages/admin/user/group/overview/overview.qtpl:10
		qw422016.N().S(`<table><thead><tr>`)
//line pages/admin/user/group/overview/overview.qtpl:14
		if p.canUpdate || p.canDelete {
//line pages/admin/user/group/overview/overview.qtpl:14
			qw422016.N().S(`<th><input type="checkbox" name="check"></th><th></th>`)
//line pages/admin/user/group/overview/overview.qtpl:17
		}
//line pages/admin/user/group/overview/overview.qtpl:17
		qw422016.N().S(`<th></th>`)
//line pages/admin/user/group/overview/overview.qtpl:19
		qw422016.N().S(p.filter.RenderOverviewColumnTableHeaders(p.GetCoreContext()))
//line pages/admin/user/group/overview/overview.qtpl:19
		qw422016.N().S(`</tr></thead><tbody>`)
//line pages/admin/user/group/overview/overview.qtpl:23
		for k := range p.userGroups {
//line pages/admin/user/group/overview/overview.qtpl:23
			qw422016.N().S(`<tr>`)
//line pages/admin/user/group/overview/overview.qtpl:25
			if p.canUpdate || p.canDelete {
//line pages/admin/user/group/overview/overview.qtpl:25
				qw422016.N().S(`<td><input type="checkbox" name="check" data-id="`)
//line pages/admin/user/group/overview/overview.qtpl:26
				qw422016.E().S(p.userGroups[k].ID())
//line pages/admin/user/group/overview/overview.qtpl:26
				qw422016.N().S(`"></td>`)
//line pages/admin/user/group/overview/overview.qtpl:27
				qw422016.N().S(`<td><a href="`)
//line pages/admin/user/group/overview/overview.qtpl:28
				qw422016.E().S(p.AdminURL())
//line pages/admin/user/group/overview/overview.qtpl:28
				qw422016.N().S(`/UserGroup/Update?id=`)
//line pages/admin/user/group/overview/overview.qtpl:28
				qw422016.E().S(p.userGroups[k].ID())
//line pages/admin/user/group/overview/overview.qtpl:28
				qw422016.N().S(`">✎</a></td>`)
//line pages/admin/user/group/overview/overview.qtpl:29
			}
//line pages/admin/user/group/overview/overview.qtpl:31
			qw422016.N().S(`<td><a href="`)
//line pages/admin/user/group/overview/overview.qtpl:32
			qw422016.E().S(p.AdminURL())
//line pages/admin/user/group/overview/overview.qtpl:32
			qw422016.N().S(`/UserGroup/View?id=`)
//line pages/admin/user/group/overview/overview.qtpl:32
			qw422016.E().S(p.userGroups[k].ID())
//line pages/admin/user/group/overview/overview.qtpl:32
			qw422016.N().S(`">`)
//line pages/admin/user/group/overview/overview.qtpl:32
			qw422016.E().S(p.TranslatePlural("detail"))
//line pages/admin/user/group/overview/overview.qtpl:32
			qw422016.N().S(`</a></td>`)
//line pages/admin/user/group/overview/overview.qtpl:34
			for key := range p.filter.ColumnsInOrder() {
//line pages/admin/user/group/overview/overview.qtpl:34
				qw422016.N().S(`<td>`)
//line pages/admin/user/group/overview/overview.qtpl:36
				switch key {
//line pages/admin/user/group/overview/overview.qtpl:37
				case 0:
//line pages/admin/user/group/overview/overview.qtpl:38
					qw422016.E().S(p.userGroups[k].ID())
//line pages/admin/user/group/overview/overview.qtpl:39
				case 1:
//line pages/admin/user/group/overview/overview.qtpl:40
					if p.userGroups[k].Active() {
//line pages/admin/user/group/overview/overview.qtpl:40
						qw422016.E().S(p.Translate("yes_"))
//line pages/admin/user/group/overview/overview.qtpl:40
					} else {
//line pages/admin/user/group/overview/overview.qtpl:40
						qw422016.E().S(p.Translate("no_"))
//line pages/admin/user/group/overview/overview.qtpl:40
					}
//line pages/admin/user/group/overview/overview.qtpl:41
				case 2:
//line pages/admin/user/group/overview/overview.qtpl:41
					qw422016.N().S(`<a href="`)
//line pages/admin/user/group/overview/overview.qtpl:42
					qw422016.E().S(p.AdminURL())
//line pages/admin/user/group/overview/overview.qtpl:42
					qw422016.N().S(`/User/View?id=`)
//line pages/admin/user/group/overview/overview.qtpl:42
					qw422016.E().S(p.userGroups[k].CreatedByID())
//line pages/admin/user/group/overview/overview.qtpl:42
					qw422016.N().S(`">`)
//line pages/admin/user/group/overview/overview.qtpl:43
					qw422016.E().S(p.rendererService.CreatedBy(p.userGroups[k], p.language.ID()))
//line pages/admin/user/group/overview/overview.qtpl:43
					qw422016.N().S(`</a>`)
//line pages/admin/user/group/overview/overview.qtpl:45
				case 3:
//line pages/admin/user/group/overview/overview.qtpl:46
					qw422016.E().S(p.userGroups[k].CreatedAt().Format(time.RFC3339[0:9]))
//line pages/admin/user/group/overview/overview.qtpl:47
				case 4:
//line pages/admin/user/group/overview/overview.qtpl:48
					if p.userGroups[k].IsUpdated() {
//line pages/admin/user/group/overview/overview.qtpl:48
						qw422016.N().S(`<a href="`)
//line pages/admin/user/group/overview/overview.qtpl:49
						qw422016.E().S(p.AdminURL())
//line pages/admin/user/group/overview/overview.qtpl:49
						qw422016.N().S(`/User/View?id=`)
//line pages/admin/user/group/overview/overview.qtpl:49
						qw422016.E().S(*p.userGroups[k].UpdatedByID())
//line pages/admin/user/group/overview/overview.qtpl:49
						qw422016.N().S(`">`)
//line pages/admin/user/group/overview/overview.qtpl:50
						qw422016.E().S(p.rendererService.UpdatedBy(p.userGroups[k], p.language.ID()))
//line pages/admin/user/group/overview/overview.qtpl:50
						qw422016.N().S(`</a>`)
//line pages/admin/user/group/overview/overview.qtpl:52
					}
//line pages/admin/user/group/overview/overview.qtpl:53
				case 5:
//line pages/admin/user/group/overview/overview.qtpl:54
					if p.userGroups[k].UpdatedAt() != nil {
//line pages/admin/user/group/overview/overview.qtpl:54
						qw422016.E().S(p.userGroups[k].UpdatedAt().Format(time.RFC3339[0:9]))
//line pages/admin/user/group/overview/overview.qtpl:54
					}
//line pages/admin/user/group/overview/overview.qtpl:55
				case 6:
//line pages/admin/user/group/overview/overview.qtpl:56
					if p.userGroups[k].LocalizedName() != nil {
//line pages/admin/user/group/overview/overview.qtpl:56
						qw422016.E().S(*p.userGroups[k].LocalizedName())
//line pages/admin/user/group/overview/overview.qtpl:56
					}
//line pages/admin/user/group/overview/overview.qtpl:57
				case 7:
//line pages/admin/user/group/overview/overview.qtpl:58
					qw422016.E().V(p.userGroups[k].UserRightsCount())
//line pages/admin/user/group/overview/overview.qtpl:59
				case 8:
//line pages/admin/user/group/overview/overview.qtpl:60
					qw422016.E().V(p.userGroups[k].CurrenciesCount())
//line pages/admin/user/group/overview/overview.qtpl:61
				}
//line pages/admin/user/group/overview/overview.qtpl:61
				qw422016.N().S(`</td>`)
//line pages/admin/user/group/overview/overview.qtpl:63
			}
//line pages/admin/user/group/overview/overview.qtpl:63
			qw422016.N().S(`</tr>`)
//line pages/admin/user/group/overview/overview.qtpl:65
		}
//line pages/admin/user/group/overview/overview.qtpl:65
		qw422016.N().S(`</tbody></table>`)
//line pages/admin/user/group/overview/overview.qtpl:68
	} else {
//line pages/admin/user/group/overview/overview.qtpl:69
		qw422016.E().S(p.Translate("noResultsFound"))
//line pages/admin/user/group/overview/overview.qtpl:70
	}
//line pages/admin/user/group/overview/overview.qtpl:70
	qw422016.N().S(`</main>`)
//line pages/admin/user/group/overview/overview.qtpl:72
}

//line pages/admin/user/group/overview/overview.qtpl:72
func (p *Page) WriteContent(qq422016 qtio422016.Writer) {
//line pages/admin/user/group/overview/overview.qtpl:72
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/admin/user/group/overview/overview.qtpl:72
	p.StreamContent(qw422016)
//line pages/admin/user/group/overview/overview.qtpl:72
	qt422016.ReleaseWriter(qw422016)
//line pages/admin/user/group/overview/overview.qtpl:72
}

//line pages/admin/user/group/overview/overview.qtpl:72
func (p *Page) Content() string {
//line pages/admin/user/group/overview/overview.qtpl:72
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/admin/user/group/overview/overview.qtpl:72
	p.WriteContent(qb422016)
//line pages/admin/user/group/overview/overview.qtpl:72
	qs422016 := string(qb422016.B)
//line pages/admin/user/group/overview/overview.qtpl:72
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/admin/user/group/overview/overview.qtpl:72
	return qs422016
//line pages/admin/user/group/overview/overview.qtpl:72
}

//line pages/admin/user/group/overview/overview.qtpl:74
func (p *Page) StreamStylesheets(qw422016 *qt422016.Writer) {
//line pages/admin/user/group/overview/overview.qtpl:75
	if p.filter.ShouldShowSearch() {
//line pages/admin/user/group/overview/overview.qtpl:75
		qw422016.N().S(`<link rel="stylesheet" href="/c/a/f.css">`)
//line pages/admin/user/group/overview/overview.qtpl:77
	}
//line pages/admin/user/group/overview/overview.qtpl:78
}

//line pages/admin/user/group/overview/overview.qtpl:78
func (p *Page) WriteStylesheets(qq422016 qtio422016.Writer) {
//line pages/admin/user/group/overview/overview.qtpl:78
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/admin/user/group/overview/overview.qtpl:78
	p.StreamStylesheets(qw422016)
//line pages/admin/user/group/overview/overview.qtpl:78
	qt422016.ReleaseWriter(qw422016)
//line pages/admin/user/group/overview/overview.qtpl:78
}

//line pages/admin/user/group/overview/overview.qtpl:78
func (p *Page) Stylesheets() string {
//line pages/admin/user/group/overview/overview.qtpl:78
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/admin/user/group/overview/overview.qtpl:78
	p.WriteStylesheets(qb422016)
//line pages/admin/user/group/overview/overview.qtpl:78
	qs422016 := string(qb422016.B)
//line pages/admin/user/group/overview/overview.qtpl:78
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/admin/user/group/overview/overview.qtpl:78
	return qs422016
//line pages/admin/user/group/overview/overview.qtpl:78
}

//line pages/admin/user/group/overview/overview.qtpl:80
func (p *Page) StreamJavascripts(qw422016 *qt422016.Writer) {
//line pages/admin/user/group/overview/overview.qtpl:81
	if p.filter.ShouldShowSearch() {
//line pages/admin/user/group/overview/overview.qtpl:81
		qw422016.N().S(`<script src="/j/a/f.js"></script>`)
//line pages/admin/user/group/overview/overview.qtpl:83
	}
//line pages/admin/user/group/overview/overview.qtpl:84
	if len(p.userGroups) > 0 {
//line pages/admin/user/group/overview/overview.qtpl:84
		qw422016.N().S(`<script src="/j/a/o.js"></script>`)
//line pages/admin/user/group/overview/overview.qtpl:86
		qw422016.N().S(p.rendererService.DefaultOverviewTranslations(p.GetCoreContext()))
//line pages/admin/user/group/overview/overview.qtpl:87
	}
//line pages/admin/user/group/overview/overview.qtpl:88
}

//line pages/admin/user/group/overview/overview.qtpl:88
func (p *Page) WriteJavascripts(qq422016 qtio422016.Writer) {
//line pages/admin/user/group/overview/overview.qtpl:88
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/admin/user/group/overview/overview.qtpl:88
	p.StreamJavascripts(qw422016)
//line pages/admin/user/group/overview/overview.qtpl:88
	qt422016.ReleaseWriter(qw422016)
//line pages/admin/user/group/overview/overview.qtpl:88
}

//line pages/admin/user/group/overview/overview.qtpl:88
func (p *Page) Javascripts() string {
//line pages/admin/user/group/overview/overview.qtpl:88
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/admin/user/group/overview/overview.qtpl:88
	p.WriteJavascripts(qb422016)
//line pages/admin/user/group/overview/overview.qtpl:88
	qs422016 := string(qb422016.B)
//line pages/admin/user/group/overview/overview.qtpl:88
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/admin/user/group/overview/overview.qtpl:88
	return qs422016
//line pages/admin/user/group/overview/overview.qtpl:88
}
