// Code generated by qtc from "overview.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line pages/forum/overview/overview.qtpl:1
package overview

//line pages/forum/overview/overview.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line pages/forum/overview/overview.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line pages/forum/overview/overview.qtpl:1
func (p *Page) StreamTitle(qw422016 *qt422016.Writer) {
//line pages/forum/overview/overview.qtpl:1
	qw422016.E().S(p.TranslatePlural("forum"))
//line pages/forum/overview/overview.qtpl:1
}

//line pages/forum/overview/overview.qtpl:1
func (p *Page) WriteTitle(qq422016 qtio422016.Writer) {
//line pages/forum/overview/overview.qtpl:1
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/forum/overview/overview.qtpl:1
	p.StreamTitle(qw422016)
//line pages/forum/overview/overview.qtpl:1
	qt422016.ReleaseWriter(qw422016)
//line pages/forum/overview/overview.qtpl:1
}

//line pages/forum/overview/overview.qtpl:1
func (p *Page) Title() string {
//line pages/forum/overview/overview.qtpl:1
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/forum/overview/overview.qtpl:1
	p.WriteTitle(qb422016)
//line pages/forum/overview/overview.qtpl:1
	qs422016 := string(qb422016.B)
//line pages/forum/overview/overview.qtpl:1
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/forum/overview/overview.qtpl:1
	return qs422016
//line pages/forum/overview/overview.qtpl:1
}

//line pages/forum/overview/overview.qtpl:3
func (p *Page) StreamContent(qw422016 *qt422016.Writer) {
//line pages/forum/overview/overview.qtpl:3
	qw422016.N().S(`<div class="content">`)
//line pages/forum/overview/overview.qtpl:5
	if len(p.forums) > 0 {
//line pages/forum/overview/overview.qtpl:5
		qw422016.N().S(`<table>`)
//line pages/forum/overview/overview.qtpl:7
		for k := range p.forums {
//line pages/forum/overview/overview.qtpl:7
			qw422016.N().S(`<tr><td><table><tr><th></th><th>`)
//line pages/forum/overview/overview.qtpl:13
			qw422016.E().S(p.TranslatePlural("topic"))
//line pages/forum/overview/overview.qtpl:13
			qw422016.N().S(`</th><th>`)
//line pages/forum/overview/overview.qtpl:14
			qw422016.E().S(p.TranslatePlural("post"))
//line pages/forum/overview/overview.qtpl:14
			qw422016.N().S(`</th><th>`)
//line pages/forum/overview/overview.qtpl:15
			qw422016.E().S(p.Translate("createdBy"))
//line pages/forum/overview/overview.qtpl:15
			qw422016.N().S(`</th></tr><tr><td><a href="/Forum?id=`)
//line pages/forum/overview/overview.qtpl:19
			qw422016.E().S(p.forums[k].ID())
//line pages/forum/overview/overview.qtpl:19
			qw422016.N().S(`">`)
//line pages/forum/overview/overview.qtpl:19
			qw422016.E().S(p.forums[k].Name())
//line pages/forum/overview/overview.qtpl:19
			qw422016.N().S(`</a></td><td>`)
//line pages/forum/overview/overview.qtpl:21
			qw422016.E().S(p.forums[k].TopicsCountAsString())
//line pages/forum/overview/overview.qtpl:21
			qw422016.N().S(`</td><td>`)
//line pages/forum/overview/overview.qtpl:22
			qw422016.E().S(p.forums[k].PostsCountAsString())
//line pages/forum/overview/overview.qtpl:22
			qw422016.N().S(`</td><td>`)
//line pages/forum/overview/overview.qtpl:23
			qw422016.E().S(p.rendererService.CreatedBy(p.forums[k], p.language.ID()))
//line pages/forum/overview/overview.qtpl:23
			qw422016.N().S(`</td></tr></table></td></tr>`)
//line pages/forum/overview/overview.qtpl:28
		}
//line pages/forum/overview/overview.qtpl:28
		qw422016.N().S(`</table>`)
//line pages/forum/overview/overview.qtpl:30
	} else {
//line pages/forum/overview/overview.qtpl:30
		qw422016.N().S(`<p>`)
//line pages/forum/overview/overview.qtpl:31
		qw422016.E().S(p.TranslatePlural("thereIsNoForumToDisplay"))
//line pages/forum/overview/overview.qtpl:31
		qw422016.N().S(`</p>`)
//line pages/forum/overview/overview.qtpl:32
	}
//line pages/forum/overview/overview.qtpl:32
	qw422016.N().S(`</div>`)
//line pages/forum/overview/overview.qtpl:34
}

//line pages/forum/overview/overview.qtpl:34
func (p *Page) WriteContent(qq422016 qtio422016.Writer) {
//line pages/forum/overview/overview.qtpl:34
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/forum/overview/overview.qtpl:34
	p.StreamContent(qw422016)
//line pages/forum/overview/overview.qtpl:34
	qt422016.ReleaseWriter(qw422016)
//line pages/forum/overview/overview.qtpl:34
}

//line pages/forum/overview/overview.qtpl:34
func (p *Page) Content() string {
//line pages/forum/overview/overview.qtpl:34
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/forum/overview/overview.qtpl:34
	p.WriteContent(qb422016)
//line pages/forum/overview/overview.qtpl:34
	qs422016 := string(qb422016.B)
//line pages/forum/overview/overview.qtpl:34
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/forum/overview/overview.qtpl:34
	return qs422016
//line pages/forum/overview/overview.qtpl:34
}
