// Code generated by qtc from "view.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line pages/admin/domain/view/view.qtpl:1
package view

//line pages/admin/domain/view/view.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line pages/admin/domain/view/view.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line pages/admin/domain/view/view.qtpl:1
func (p *Page) StreamTitle(qw422016 *qt422016.Writer) {
//line pages/admin/domain/view/view.qtpl:1
	qw422016.E().S(p.TranslatePlural("domain"))
//line pages/admin/domain/view/view.qtpl:1
	qw422016.N().S(` > `)
//line pages/admin/domain/view/view.qtpl:1
	qw422016.E().S(p.domain.Host())
//line pages/admin/domain/view/view.qtpl:1
}

//line pages/admin/domain/view/view.qtpl:1
func (p *Page) WriteTitle(qq422016 qtio422016.Writer) {
//line pages/admin/domain/view/view.qtpl:1
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/admin/domain/view/view.qtpl:1
	p.StreamTitle(qw422016)
//line pages/admin/domain/view/view.qtpl:1
	qt422016.ReleaseWriter(qw422016)
//line pages/admin/domain/view/view.qtpl:1
}

//line pages/admin/domain/view/view.qtpl:1
func (p *Page) Title() string {
//line pages/admin/domain/view/view.qtpl:1
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/admin/domain/view/view.qtpl:1
	p.WriteTitle(qb422016)
//line pages/admin/domain/view/view.qtpl:1
	qs422016 := string(qb422016.B)
//line pages/admin/domain/view/view.qtpl:1
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/admin/domain/view/view.qtpl:1
	return qs422016
//line pages/admin/domain/view/view.qtpl:1
}

//line pages/admin/domain/view/view.qtpl:3
func (p *Page) StreamContent(qw422016 *qt422016.Writer) {
//line pages/admin/domain/view/view.qtpl:3
	qw422016.N().S(`<main class="content"><h1>`)
//line pages/admin/domain/view/view.qtpl:5
	qw422016.E().S(p.TranslatePlural("domain"))
//line pages/admin/domain/view/view.qtpl:5
	qw422016.E().S(" > ")
//line pages/admin/domain/view/view.qtpl:5
	qw422016.E().S(p.domain.Host())
//line pages/admin/domain/view/view.qtpl:5
	qw422016.N().S(`</h1><p><a href="`)
//line pages/admin/domain/view/view.qtpl:8
	qw422016.E().S(p.AdminURL())
//line pages/admin/domain/view/view.qtpl:8
	qw422016.N().S(`/Domain">`)
//line pages/admin/domain/view/view.qtpl:8
	qw422016.E().S(p.Translate("backToOverview"))
//line pages/admin/domain/view/view.qtpl:8
	qw422016.N().S(`</a><br><a href="`)
//line pages/admin/domain/view/view.qtpl:9
	qw422016.E().S(p.AdminURL())
//line pages/admin/domain/view/view.qtpl:9
	qw422016.N().S(`/Domain/Update?id=`)
//line pages/admin/domain/view/view.qtpl:9
	qw422016.E().S(p.domain.ID())
//line pages/admin/domain/view/view.qtpl:9
	qw422016.N().S(`">`)
//line pages/admin/domain/view/view.qtpl:9
	qw422016.E().S("✎ ")
//line pages/admin/domain/view/view.qtpl:9
	qw422016.E().S(p.Translate("update"))
//line pages/admin/domain/view/view.qtpl:9
	qw422016.N().S(`</a></p><p>`)
//line pages/admin/domain/view/view.qtpl:11
	qw422016.E().S(p.Translate("active"))
//line pages/admin/domain/view/view.qtpl:11
	qw422016.N().S(`:`)
//line pages/admin/domain/view/view.qtpl:11
	qw422016.N().S(` `)
//line pages/admin/domain/view/view.qtpl:11
	if p.domain.Active() {
//line pages/admin/domain/view/view.qtpl:11
		qw422016.E().S(p.Translate("yes_"))
//line pages/admin/domain/view/view.qtpl:11
	} else {
//line pages/admin/domain/view/view.qtpl:11
		qw422016.E().S(p.Translate("no_"))
//line pages/admin/domain/view/view.qtpl:11
	}
//line pages/admin/domain/view/view.qtpl:11
	qw422016.N().S(`</p><p>`)
//line pages/admin/domain/view/view.qtpl:12
	qw422016.E().S(p.Translate("language"))
//line pages/admin/domain/view/view.qtpl:12
	qw422016.N().S(`:`)
//line pages/admin/domain/view/view.qtpl:12
	qw422016.N().S(` `)
//line pages/admin/domain/view/view.qtpl:12
	if p.domainLanguage != nil {
//line pages/admin/domain/view/view.qtpl:12
		qw422016.E().S(p.domainLanguage.Translate(p.language.ID()))
//line pages/admin/domain/view/view.qtpl:12
	}
//line pages/admin/domain/view/view.qtpl:12
	qw422016.N().S(`</p></main>`)
//line pages/admin/domain/view/view.qtpl:14
}

//line pages/admin/domain/view/view.qtpl:14
func (p *Page) WriteContent(qq422016 qtio422016.Writer) {
//line pages/admin/domain/view/view.qtpl:14
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/admin/domain/view/view.qtpl:14
	p.StreamContent(qw422016)
//line pages/admin/domain/view/view.qtpl:14
	qt422016.ReleaseWriter(qw422016)
//line pages/admin/domain/view/view.qtpl:14
}

//line pages/admin/domain/view/view.qtpl:14
func (p *Page) Content() string {
//line pages/admin/domain/view/view.qtpl:14
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/admin/domain/view/view.qtpl:14
	p.WriteContent(qb422016)
//line pages/admin/domain/view/view.qtpl:14
	qs422016 := string(qb422016.B)
//line pages/admin/domain/view/view.qtpl:14
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/admin/domain/view/view.qtpl:14
	return qs422016
//line pages/admin/domain/view/view.qtpl:14
}
