// Code generated by qtc from "base.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line pages/base/base.qtpl:1
package base

//line pages/base/base.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line pages/base/base.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line pages/base/base.qtpl:2
type BasePage interface {
//line pages/base/base.qtpl:2
	Title() string
//line pages/base/base.qtpl:2
	StreamTitle(qw422016 *qt422016.Writer)
//line pages/base/base.qtpl:2
	WriteTitle(qq422016 qtio422016.Writer)
//line pages/base/base.qtpl:2
	Menu() string
//line pages/base/base.qtpl:2
	StreamMenu(qw422016 *qt422016.Writer)
//line pages/base/base.qtpl:2
	WriteMenu(qq422016 qtio422016.Writer)
//line pages/base/base.qtpl:2
	Content() string
//line pages/base/base.qtpl:2
	StreamContent(qw422016 *qt422016.Writer)
//line pages/base/base.qtpl:2
	WriteContent(qq422016 qtio422016.Writer)
//line pages/base/base.qtpl:2
	Stylesheets() string
//line pages/base/base.qtpl:2
	StreamStylesheets(qw422016 *qt422016.Writer)
//line pages/base/base.qtpl:2
	WriteStylesheets(qq422016 qtio422016.Writer)
//line pages/base/base.qtpl:2
	mainStylesheets() string
//line pages/base/base.qtpl:2
	streammainStylesheets(qw422016 *qt422016.Writer)
//line pages/base/base.qtpl:2
	writemainStylesheets(qq422016 qtio422016.Writer)
//line pages/base/base.qtpl:2
	Javascripts() string
//line pages/base/base.qtpl:2
	StreamJavascripts(qw422016 *qt422016.Writer)
//line pages/base/base.qtpl:2
	WriteJavascripts(qq422016 qtio422016.Writer)
//line pages/base/base.qtpl:2
	mainJavascripts() string
//line pages/base/base.qtpl:2
	streammainJavascripts(qw422016 *qt422016.Writer)
//line pages/base/base.qtpl:2
	writemainJavascripts(qq422016 qtio422016.Writer)
//line pages/base/base.qtpl:2
}

//line pages/base/base.qtpl:13
func StreamPageTemplate(qw422016 *qt422016.Writer, p BasePage) {
//line pages/base/base.qtpl:13
	qw422016.N().S(`<!DOCTYPE html><html><head><meta charset="utf-8"><title>`)
//line pages/base/base.qtpl:18
	p.StreamTitle(qw422016)
//line pages/base/base.qtpl:18
	qw422016.N().S(`</title>`)
//line pages/base/base.qtpl:19
	p.streammainStylesheets(qw422016)
//line pages/base/base.qtpl:20
	p.StreamStylesheets(qw422016)
//line pages/base/base.qtpl:20
	qw422016.N().S(`</head><body>`)
//line pages/base/base.qtpl:23
	p.StreamMenu(qw422016)
//line pages/base/base.qtpl:24
	p.StreamContent(qw422016)
//line pages/base/base.qtpl:25
	p.streammainJavascripts(qw422016)
//line pages/base/base.qtpl:26
	p.StreamJavascripts(qw422016)
//line pages/base/base.qtpl:27
	qw422016.N().S(`</body></html>`)
//line pages/base/base.qtpl:29
}

//line pages/base/base.qtpl:29
func WritePageTemplate(qq422016 qtio422016.Writer, p BasePage) {
//line pages/base/base.qtpl:29
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/base/base.qtpl:29
	StreamPageTemplate(qw422016, p)
//line pages/base/base.qtpl:29
	qt422016.ReleaseWriter(qw422016)
//line pages/base/base.qtpl:29
}

//line pages/base/base.qtpl:29
func PageTemplate(p BasePage) string {
//line pages/base/base.qtpl:29
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/base/base.qtpl:29
	WritePageTemplate(qb422016, p)
//line pages/base/base.qtpl:29
	qs422016 := string(qb422016.B)
//line pages/base/base.qtpl:29
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/base/base.qtpl:29
	return qs422016
//line pages/base/base.qtpl:29
}

//line pages/base/base.qtpl:31
func (p *Page) StreamTitle(qw422016 *qt422016.Writer) {
//line pages/base/base.qtpl:31
}

//line pages/base/base.qtpl:31
func (p *Page) WriteTitle(qq422016 qtio422016.Writer) {
//line pages/base/base.qtpl:31
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/base/base.qtpl:31
	p.StreamTitle(qw422016)
//line pages/base/base.qtpl:31
	qt422016.ReleaseWriter(qw422016)
//line pages/base/base.qtpl:31
}

//line pages/base/base.qtpl:31
func (p *Page) Title() string {
//line pages/base/base.qtpl:31
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/base/base.qtpl:31
	p.WriteTitle(qb422016)
//line pages/base/base.qtpl:31
	qs422016 := string(qb422016.B)
//line pages/base/base.qtpl:31
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/base/base.qtpl:31
	return qs422016
//line pages/base/base.qtpl:31
}

//line pages/base/base.qtpl:33
func (p *Page) StreamMenu(qw422016 *qt422016.Writer) {
//line pages/base/base.qtpl:33
	qw422016.N().S(`<header><a href="/">`)
//line pages/base/base.qtpl:35
	qw422016.E().S(p.Translate("home"))
//line pages/base/base.qtpl:35
	qw422016.N().S(`</a><a href="/Catalog">`)
//line pages/base/base.qtpl:36
	qw422016.E().S(p.Translate("catalog"))
//line pages/base/base.qtpl:36
	qw422016.N().S(`</a><a href="/Forums">`)
//line pages/base/base.qtpl:37
	qw422016.E().S(p.TranslatePlural("forum"))
//line pages/base/base.qtpl:37
	qw422016.N().S(`</a><a href="/Cart">`)
//line pages/base/base.qtpl:38
	qw422016.E().S(p.Translate("shoppingCart"))
//line pages/base/base.qtpl:38
	qw422016.N().S(`</a>`)
//line pages/base/base.qtpl:39
	if p.IsLoggedIn() {
//line pages/base/base.qtpl:39
		qw422016.N().S(`<a href="/Account">`)
//line pages/base/base.qtpl:39
		qw422016.E().S(p.Translate("myAccount"))
//line pages/base/base.qtpl:39
		qw422016.N().S(`</a>`)
//line pages/base/base.qtpl:39
	}
//line pages/base/base.qtpl:40
	if !p.IsLoggedIn() {
//line pages/base/base.qtpl:40
		qw422016.N().S(`<a href="/Login">`)
//line pages/base/base.qtpl:40
		qw422016.E().S(p.Translate("login"))
//line pages/base/base.qtpl:40
		qw422016.N().S(`</a>`)
//line pages/base/base.qtpl:40
	}
//line pages/base/base.qtpl:41
	if p.IsLoggedIn() {
//line pages/base/base.qtpl:41
		qw422016.N().S(`<a href="/Logout">`)
//line pages/base/base.qtpl:41
		qw422016.E().S(p.Translate("logout"))
//line pages/base/base.qtpl:41
		qw422016.N().S(`</a>`)
//line pages/base/base.qtpl:41
	}
//line pages/base/base.qtpl:42
	if !p.IsLoggedIn() {
//line pages/base/base.qtpl:42
		qw422016.N().S(`<a href="/ForgotPassword">`)
//line pages/base/base.qtpl:42
		qw422016.E().S(p.Translate("forgotPassword"))
//line pages/base/base.qtpl:42
		qw422016.N().S(`</a>`)
//line pages/base/base.qtpl:42
	}
//line pages/base/base.qtpl:43
	if p.IsLoggedIn() && p.HasAdminAccess() {
//line pages/base/base.qtpl:43
		qw422016.N().S(`<a href="`)
//line pages/base/base.qtpl:44
		qw422016.E().S(p.AdminURL())
//line pages/base/base.qtpl:44
		qw422016.N().S(`">`)
//line pages/base/base.qtpl:44
		qw422016.E().S(p.Translate("admin"))
//line pages/base/base.qtpl:44
		qw422016.N().S(`</a>`)
//line pages/base/base.qtpl:45
	}
//line pages/base/base.qtpl:46
	if p.HasPprofEnabled() {
//line pages/base/base.qtpl:46
		qw422016.N().S(`<a href="`)
//line pages/base/base.qtpl:47
		qw422016.E().S(p.PprofURL())
//line pages/base/base.qtpl:47
		qw422016.N().S(`">Pprof</a>`)
//line pages/base/base.qtpl:48
	}
//line pages/base/base.qtpl:48
	qw422016.N().S(`</header>`)
//line pages/base/base.qtpl:50
}

//line pages/base/base.qtpl:50
func (p *Page) WriteMenu(qq422016 qtio422016.Writer) {
//line pages/base/base.qtpl:50
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/base/base.qtpl:50
	p.StreamMenu(qw422016)
//line pages/base/base.qtpl:50
	qt422016.ReleaseWriter(qw422016)
//line pages/base/base.qtpl:50
}

//line pages/base/base.qtpl:50
func (p *Page) Menu() string {
//line pages/base/base.qtpl:50
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/base/base.qtpl:50
	p.WriteMenu(qb422016)
//line pages/base/base.qtpl:50
	qs422016 := string(qb422016.B)
//line pages/base/base.qtpl:50
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/base/base.qtpl:50
	return qs422016
//line pages/base/base.qtpl:50
}

//line pages/base/base.qtpl:52
func (p *Page) streammainStylesheets(qw422016 *qt422016.Writer) {
//line pages/base/base.qtpl:52
	qw422016.N().S(`<link rel="stylesheet" href="/c/m.css">`)
//line pages/base/base.qtpl:54
	if p.IsDevelopment() {
//line pages/base/base.qtpl:54
		qw422016.N().S(`<link rel="stylesheet" href="/c/devBar.css">`)
//line pages/base/base.qtpl:56
	}
//line pages/base/base.qtpl:57
}

//line pages/base/base.qtpl:57
func (p *Page) writemainStylesheets(qq422016 qtio422016.Writer) {
//line pages/base/base.qtpl:57
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/base/base.qtpl:57
	p.streammainStylesheets(qw422016)
//line pages/base/base.qtpl:57
	qt422016.ReleaseWriter(qw422016)
//line pages/base/base.qtpl:57
}

//line pages/base/base.qtpl:57
func (p *Page) mainStylesheets() string {
//line pages/base/base.qtpl:57
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/base/base.qtpl:57
	p.writemainStylesheets(qb422016)
//line pages/base/base.qtpl:57
	qs422016 := string(qb422016.B)
//line pages/base/base.qtpl:57
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/base/base.qtpl:57
	return qs422016
//line pages/base/base.qtpl:57
}

//line pages/base/base.qtpl:59
func (p *Page) streammainJavascripts(qw422016 *qt422016.Writer) {
//line pages/base/base.qtpl:60
	if p.HasFlashMessage() {
//line pages/base/base.qtpl:60
		qw422016.N().S(`<script src="/j/flashMessage.js"></script>`)
//line pages/base/base.qtpl:62
	}
//line pages/base/base.qtpl:63
	if p.IsDevelopment() {
//line pages/base/base.qtpl:63
		qw422016.N().S(`<script src="/j/devBar.js"></script>`)
//line pages/base/base.qtpl:65
	}
//line pages/base/base.qtpl:66
}

//line pages/base/base.qtpl:66
func (p *Page) writemainJavascripts(qq422016 qtio422016.Writer) {
//line pages/base/base.qtpl:66
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/base/base.qtpl:66
	p.streammainJavascripts(qw422016)
//line pages/base/base.qtpl:66
	qt422016.ReleaseWriter(qw422016)
//line pages/base/base.qtpl:66
}

//line pages/base/base.qtpl:66
func (p *Page) mainJavascripts() string {
//line pages/base/base.qtpl:66
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/base/base.qtpl:66
	p.writemainJavascripts(qb422016)
//line pages/base/base.qtpl:66
	qs422016 := string(qb422016.B)
//line pages/base/base.qtpl:66
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/base/base.qtpl:66
	return qs422016
//line pages/base/base.qtpl:66
}

//line pages/base/base.qtpl:68
func (p *Page) StreamContent(qw422016 *qt422016.Writer) {
//line pages/base/base.qtpl:68
}

//line pages/base/base.qtpl:68
func (p *Page) WriteContent(qq422016 qtio422016.Writer) {
//line pages/base/base.qtpl:68
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/base/base.qtpl:68
	p.StreamContent(qw422016)
//line pages/base/base.qtpl:68
	qt422016.ReleaseWriter(qw422016)
//line pages/base/base.qtpl:68
}

//line pages/base/base.qtpl:68
func (p *Page) Content() string {
//line pages/base/base.qtpl:68
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/base/base.qtpl:68
	p.WriteContent(qb422016)
//line pages/base/base.qtpl:68
	qs422016 := string(qb422016.B)
//line pages/base/base.qtpl:68
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/base/base.qtpl:68
	return qs422016
//line pages/base/base.qtpl:68
}

//line pages/base/base.qtpl:70
func (p *Page) StreamStylesheets(qw422016 *qt422016.Writer) {
//line pages/base/base.qtpl:70
}

//line pages/base/base.qtpl:70
func (p *Page) WriteStylesheets(qq422016 qtio422016.Writer) {
//line pages/base/base.qtpl:70
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/base/base.qtpl:70
	p.StreamStylesheets(qw422016)
//line pages/base/base.qtpl:70
	qt422016.ReleaseWriter(qw422016)
//line pages/base/base.qtpl:70
}

//line pages/base/base.qtpl:70
func (p *Page) Stylesheets() string {
//line pages/base/base.qtpl:70
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/base/base.qtpl:70
	p.WriteStylesheets(qb422016)
//line pages/base/base.qtpl:70
	qs422016 := string(qb422016.B)
//line pages/base/base.qtpl:70
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/base/base.qtpl:70
	return qs422016
//line pages/base/base.qtpl:70
}

//line pages/base/base.qtpl:72
func (p *Page) StreamJavascripts(qw422016 *qt422016.Writer) {
//line pages/base/base.qtpl:72
}

//line pages/base/base.qtpl:72
func (p *Page) WriteJavascripts(qq422016 qtio422016.Writer) {
//line pages/base/base.qtpl:72
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/base/base.qtpl:72
	p.StreamJavascripts(qw422016)
//line pages/base/base.qtpl:72
	qt422016.ReleaseWriter(qw422016)
//line pages/base/base.qtpl:72
}

//line pages/base/base.qtpl:72
func (p *Page) Javascripts() string {
//line pages/base/base.qtpl:72
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/base/base.qtpl:72
	p.WriteJavascripts(qb422016)
//line pages/base/base.qtpl:72
	qs422016 := string(qb422016.B)
//line pages/base/base.qtpl:72
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/base/base.qtpl:72
	return qs422016
//line pages/base/base.qtpl:72
}
