// Code generated by qtc from "edit.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line pages/forum/post/edit/edit.qtpl:1
package edit

//line pages/forum/post/edit/edit.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line pages/forum/post/edit/edit.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line pages/forum/post/edit/edit.qtpl:1
func (p *Page) StreamTitle(qw422016 *qt422016.Writer) {
//line pages/forum/post/edit/edit.qtpl:1
	qw422016.E().S(*p.post.Title())
//line pages/forum/post/edit/edit.qtpl:1
}

//line pages/forum/post/edit/edit.qtpl:1
func (p *Page) WriteTitle(qq422016 qtio422016.Writer) {
//line pages/forum/post/edit/edit.qtpl:1
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/forum/post/edit/edit.qtpl:1
	p.StreamTitle(qw422016)
//line pages/forum/post/edit/edit.qtpl:1
	qt422016.ReleaseWriter(qw422016)
//line pages/forum/post/edit/edit.qtpl:1
}

//line pages/forum/post/edit/edit.qtpl:1
func (p *Page) Title() string {
//line pages/forum/post/edit/edit.qtpl:1
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/forum/post/edit/edit.qtpl:1
	p.WriteTitle(qb422016)
//line pages/forum/post/edit/edit.qtpl:1
	qs422016 := string(qb422016.B)
//line pages/forum/post/edit/edit.qtpl:1
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/forum/post/edit/edit.qtpl:1
	return qs422016
//line pages/forum/post/edit/edit.qtpl:1
}

//line pages/forum/post/edit/edit.qtpl:3
func (p *Page) StreamContent(qw422016 *qt422016.Writer) {
//line pages/forum/post/edit/edit.qtpl:3
	qw422016.N().S(`<div class="content">`)
//line pages/forum/post/edit/edit.qtpl:5
	qw422016.N().S(`EDIT</div>`)
//line pages/forum/post/edit/edit.qtpl:8
}

//line pages/forum/post/edit/edit.qtpl:8
func (p *Page) WriteContent(qq422016 qtio422016.Writer) {
//line pages/forum/post/edit/edit.qtpl:8
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/forum/post/edit/edit.qtpl:8
	p.StreamContent(qw422016)
//line pages/forum/post/edit/edit.qtpl:8
	qt422016.ReleaseWriter(qw422016)
//line pages/forum/post/edit/edit.qtpl:8
}

//line pages/forum/post/edit/edit.qtpl:8
func (p *Page) Content() string {
//line pages/forum/post/edit/edit.qtpl:8
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/forum/post/edit/edit.qtpl:8
	p.WriteContent(qb422016)
//line pages/forum/post/edit/edit.qtpl:8
	qs422016 := string(qb422016.B)
//line pages/forum/post/edit/edit.qtpl:8
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/forum/post/edit/edit.qtpl:8
	return qs422016
//line pages/forum/post/edit/edit.qtpl:8
}
