// Code generated by qtc from "createupdate.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line pages/admin/user/createupdate/createupdate.qtpl:1
package createupdate

//line pages/admin/user/createupdate/createupdate.qtpl:1
import "fmt"

//line pages/admin/user/createupdate/createupdate.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line pages/admin/user/createupdate/createupdate.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line pages/admin/user/createupdate/createupdate.qtpl:3
func (p *Page) StreamTitle(qw422016 *qt422016.Writer) {
//line pages/admin/user/createupdate/createupdate.qtpl:3
	qw422016.E().S(p.displayTitle)
//line pages/admin/user/createupdate/createupdate.qtpl:3
}

//line pages/admin/user/createupdate/createupdate.qtpl:3
func (p *Page) WriteTitle(qq422016 qtio422016.Writer) {
//line pages/admin/user/createupdate/createupdate.qtpl:3
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/admin/user/createupdate/createupdate.qtpl:3
	p.StreamTitle(qw422016)
//line pages/admin/user/createupdate/createupdate.qtpl:3
	qt422016.ReleaseWriter(qw422016)
//line pages/admin/user/createupdate/createupdate.qtpl:3
}

//line pages/admin/user/createupdate/createupdate.qtpl:3
func (p *Page) Title() string {
//line pages/admin/user/createupdate/createupdate.qtpl:3
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/admin/user/createupdate/createupdate.qtpl:3
	p.WriteTitle(qb422016)
//line pages/admin/user/createupdate/createupdate.qtpl:3
	qs422016 := string(qb422016.B)
//line pages/admin/user/createupdate/createupdate.qtpl:3
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/admin/user/createupdate/createupdate.qtpl:3
	return qs422016
//line pages/admin/user/createupdate/createupdate.qtpl:3
}

//line pages/admin/user/createupdate/createupdate.qtpl:5
func (p *Page) StreamContent(qw422016 *qt422016.Writer) {
//line pages/admin/user/createupdate/createupdate.qtpl:5
	qw422016.N().S(`<main class="content"><h1>`)
//line pages/admin/user/createupdate/createupdate.qtpl:7
	qw422016.E().S(p.displayTitle)
//line pages/admin/user/createupdate/createupdate.qtpl:7
	qw422016.N().S(`</h1>`)
//line pages/admin/user/createupdate/createupdate.qtpl:8
	qw422016.N().S(p.form.Errors())
//line pages/admin/user/createupdate/createupdate.qtpl:9
	qw422016.N().S(p.rendererService.CreatedUpdatedByLinks(p.GetCoreContext(), p.language.ID(), p.user))
//line pages/admin/user/createupdate/createupdate.qtpl:10
	qw422016.N().S(p.form.Open())
//line pages/admin/user/createupdate/createupdate.qtpl:11
	qw422016.N().S(p.form.Field("_uname"))
//line pages/admin/user/createupdate/createupdate.qtpl:12
	qw422016.N().S(p.form.Field("_t"))
//line pages/admin/user/createupdate/createupdate.qtpl:13
	qw422016.N().S(p.form.Field("active"))
//line pages/admin/user/createupdate/createupdate.qtpl:13
	qw422016.N().S(`<br>`)
//line pages/admin/user/createupdate/createupdate.qtpl:14
	qw422016.N().S(p.form.Field("firstName"))
//line pages/admin/user/createupdate/createupdate.qtpl:14
	qw422016.N().S(`<br>`)
//line pages/admin/user/createupdate/createupdate.qtpl:15
	qw422016.N().S(p.form.Field("surname"))
//line pages/admin/user/createupdate/createupdate.qtpl:15
	qw422016.N().S(`<br>`)
//line pages/admin/user/createupdate/createupdate.qtpl:16
	qw422016.N().S(p.form.Field("dateOfBirth"))
//line pages/admin/user/createupdate/createupdate.qtpl:16
	qw422016.N().S(`<br>`)
//line pages/admin/user/createupdate/createupdate.qtpl:17
	qw422016.N().S(p.form.Field("email"))
//line pages/admin/user/createupdate/createupdate.qtpl:17
	qw422016.N().S(`<br>`)
//line pages/admin/user/createupdate/createupdate.qtpl:18
	qw422016.N().S(p.form.Field("priority"))
//line pages/admin/user/createupdate/createupdate.qtpl:18
	qw422016.N().S(`<br>`)
//line pages/admin/user/createupdate/createupdate.qtpl:19
	qw422016.N().S(p.form.Field("country"))
//line pages/admin/user/createupdate/createupdate.qtpl:19
	qw422016.N().S(`<br>`)
//line pages/admin/user/createupdate/createupdate.qtpl:20
	qw422016.N().S(p.form.Field("language"))
//line pages/admin/user/createupdate/createupdate.qtpl:20
	qw422016.N().S(`<br>`)
//line pages/admin/user/createupdate/createupdate.qtpl:22
	qw422016.N().S(p.form.Field("avatar"))
//line pages/admin/user/createupdate/createupdate.qtpl:22
	qw422016.N().S(`<br>`)
//line pages/admin/user/createupdate/createupdate.qtpl:23
	if p.user.Avatar() != nil {
//line pages/admin/user/createupdate/createupdate.qtpl:23
		qw422016.N().S(`<img src="/f/`)
//line pages/admin/user/createupdate/createupdate.qtpl:24
		qw422016.E().S(*p.user.Avatar())
//line pages/admin/user/createupdate/createupdate.qtpl:24
		qw422016.N().S(`" class="imgPreview"><a href="`)
//line pages/admin/user/createupdate/createupdate.qtpl:25
		qw422016.E().S(p.AdminURL())
//line pages/admin/user/createupdate/createupdate.qtpl:25
		qw422016.N().S(`/User/RemoveAvatar?id=`)
//line pages/admin/user/createupdate/createupdate.qtpl:25
		qw422016.E().S(p.user.ID())
//line pages/admin/user/createupdate/createupdate.qtpl:25
		qw422016.N().S(`"`)
//line pages/admin/user/createupdate/createupdate.qtpl:25
		qw422016.E().S("onclick=\"return confirm('" + p.Translate("areYouSure") + "');\"")
//line pages/admin/user/createupdate/createupdate.qtpl:25
		qw422016.N().S(`>`)
//line pages/admin/user/createupdate/createupdate.qtpl:26
		qw422016.E().S(p.Translate("removeAvatar"))
//line pages/admin/user/createupdate/createupdate.qtpl:26
		qw422016.N().S(`</a>`)
//line pages/admin/user/createupdate/createupdate.qtpl:28
	}
//line pages/admin/user/createupdate/createupdate.qtpl:31
	qw422016.N().S(p.form.Field("password"))
//line pages/admin/user/createupdate/createupdate.qtpl:31
	qw422016.N().S(`<br>`)
//line pages/admin/user/createupdate/createupdate.qtpl:32
	qw422016.N().S(p.form.Field("repeatPassword"))
//line pages/admin/user/createupdate/createupdate.qtpl:32
	qw422016.N().S(`<br>`)
//line pages/admin/user/createupdate/createupdate.qtpl:34
	if p.user.ID() != "" {
//line pages/admin/user/createupdate/createupdate.qtpl:35
		qw422016.N().S(p.form.Field("defaultDeliveryAddress"))
//line pages/admin/user/createupdate/createupdate.qtpl:35
		qw422016.N().S(`<br>`)
//line pages/admin/user/createupdate/createupdate.qtpl:36
		qw422016.N().S(p.form.Field("defaultInvoiceAddress"))
//line pages/admin/user/createupdate/createupdate.qtpl:36
		qw422016.N().S(`<br>`)
//line pages/admin/user/createupdate/createupdate.qtpl:37
	}
//line pages/admin/user/createupdate/createupdate.qtpl:39
	qw422016.N().S(p.form.Field("currencies"))
//line pages/admin/user/createupdate/createupdate.qtpl:39
	qw422016.N().S(`<br>`)
//line pages/admin/user/createupdate/createupdate.qtpl:40
	qw422016.N().S(p.form.Field("biography"))
//line pages/admin/user/createupdate/createupdate.qtpl:40
	qw422016.N().S(`<br>`)
//line pages/admin/user/createupdate/createupdate.qtpl:41
	qw422016.N().S(p.form.Field("comments"))
//line pages/admin/user/createupdate/createupdate.qtpl:41
	qw422016.N().S(`<br>`)
//line pages/admin/user/createupdate/createupdate.qtpl:43
	qw422016.N().S(p.form.CreateUpdateActions("action", fmt.Sprintf("User/View?id=%s", p.user.ID())))
//line pages/admin/user/createupdate/createupdate.qtpl:43
	qw422016.N().S(`</form></main>`)
//line pages/admin/user/createupdate/createupdate.qtpl:46
}

//line pages/admin/user/createupdate/createupdate.qtpl:46
func (p *Page) WriteContent(qq422016 qtio422016.Writer) {
//line pages/admin/user/createupdate/createupdate.qtpl:46
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/admin/user/createupdate/createupdate.qtpl:46
	p.StreamContent(qw422016)
//line pages/admin/user/createupdate/createupdate.qtpl:46
	qt422016.ReleaseWriter(qw422016)
//line pages/admin/user/createupdate/createupdate.qtpl:46
}

//line pages/admin/user/createupdate/createupdate.qtpl:46
func (p *Page) Content() string {
//line pages/admin/user/createupdate/createupdate.qtpl:46
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/admin/user/createupdate/createupdate.qtpl:46
	p.WriteContent(qb422016)
//line pages/admin/user/createupdate/createupdate.qtpl:46
	qs422016 := string(qb422016.B)
//line pages/admin/user/createupdate/createupdate.qtpl:46
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/admin/user/createupdate/createupdate.qtpl:46
	return qs422016
//line pages/admin/user/createupdate/createupdate.qtpl:46
}

//line pages/admin/user/createupdate/createupdate.qtpl:48
func (p *Page) StreamStylesheets(qw422016 *qt422016.Writer) {
//line pages/admin/user/createupdate/createupdate.qtpl:49
	if p.form.ContainsSelectSearch() {
//line pages/admin/user/createupdate/createupdate.qtpl:49
		qw422016.N().S(`<link rel="stylesheet" href="/c/a/selectSearch.css"></link>`)
//line pages/admin/user/createupdate/createupdate.qtpl:51
	}
//line pages/admin/user/createupdate/createupdate.qtpl:52
}

//line pages/admin/user/createupdate/createupdate.qtpl:52
func (p *Page) WriteStylesheets(qq422016 qtio422016.Writer) {
//line pages/admin/user/createupdate/createupdate.qtpl:52
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/admin/user/createupdate/createupdate.qtpl:52
	p.StreamStylesheets(qw422016)
//line pages/admin/user/createupdate/createupdate.qtpl:52
	qt422016.ReleaseWriter(qw422016)
//line pages/admin/user/createupdate/createupdate.qtpl:52
}

//line pages/admin/user/createupdate/createupdate.qtpl:52
func (p *Page) Stylesheets() string {
//line pages/admin/user/createupdate/createupdate.qtpl:52
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/admin/user/createupdate/createupdate.qtpl:52
	p.WriteStylesheets(qb422016)
//line pages/admin/user/createupdate/createupdate.qtpl:52
	qs422016 := string(qb422016.B)
//line pages/admin/user/createupdate/createupdate.qtpl:52
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/admin/user/createupdate/createupdate.qtpl:52
	return qs422016
//line pages/admin/user/createupdate/createupdate.qtpl:52
}

//line pages/admin/user/createupdate/createupdate.qtpl:54
func (p *Page) StreamJavascripts(qw422016 *qt422016.Writer) {
//line pages/admin/user/createupdate/createupdate.qtpl:54
	qw422016.N().S(`<script src="/j/a/cu.js"></script>`)
//line pages/admin/user/createupdate/createupdate.qtpl:56
	if p.form.ContainsSelectSearch() {
//line pages/admin/user/createupdate/createupdate.qtpl:56
		qw422016.N().S(`<script src="/j/a/selectSearch.js"></script>`)
//line pages/admin/user/createupdate/createupdate.qtpl:58
	}
//line pages/admin/user/createupdate/createupdate.qtpl:59
}

//line pages/admin/user/createupdate/createupdate.qtpl:59
func (p *Page) WriteJavascripts(qq422016 qtio422016.Writer) {
//line pages/admin/user/createupdate/createupdate.qtpl:59
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/admin/user/createupdate/createupdate.qtpl:59
	p.StreamJavascripts(qw422016)
//line pages/admin/user/createupdate/createupdate.qtpl:59
	qt422016.ReleaseWriter(qw422016)
//line pages/admin/user/createupdate/createupdate.qtpl:59
}

//line pages/admin/user/createupdate/createupdate.qtpl:59
func (p *Page) Javascripts() string {
//line pages/admin/user/createupdate/createupdate.qtpl:59
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/admin/user/createupdate/createupdate.qtpl:59
	p.WriteJavascripts(qb422016)
//line pages/admin/user/createupdate/createupdate.qtpl:59
	qs422016 := string(qb422016.B)
//line pages/admin/user/createupdate/createupdate.qtpl:59
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/admin/user/createupdate/createupdate.qtpl:59
	return qs422016
//line pages/admin/user/createupdate/createupdate.qtpl:59
}
