// Code generated by qtc from "change.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line pages/account/password/change/change.qtpl:1
package change

//line pages/account/password/change/change.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line pages/account/password/change/change.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line pages/account/password/change/change.qtpl:1
func (p *Page) StreamTitle(qw422016 *qt422016.Writer) {
//line pages/account/password/change/change.qtpl:1
	qw422016.E().S(p.Translate("account"))
//line pages/account/password/change/change.qtpl:1
	qw422016.N().S(` `)
//line pages/account/password/change/change.qtpl:1
	qw422016.E().S(p.Translate("changePassword"))
//line pages/account/password/change/change.qtpl:1
}

//line pages/account/password/change/change.qtpl:1
func (p *Page) WriteTitle(qq422016 qtio422016.Writer) {
//line pages/account/password/change/change.qtpl:1
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/account/password/change/change.qtpl:1
	p.StreamTitle(qw422016)
//line pages/account/password/change/change.qtpl:1
	qt422016.ReleaseWriter(qw422016)
//line pages/account/password/change/change.qtpl:1
}

//line pages/account/password/change/change.qtpl:1
func (p *Page) Title() string {
//line pages/account/password/change/change.qtpl:1
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/account/password/change/change.qtpl:1
	p.WriteTitle(qb422016)
//line pages/account/password/change/change.qtpl:1
	qs422016 := string(qb422016.B)
//line pages/account/password/change/change.qtpl:1
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/account/password/change/change.qtpl:1
	return qs422016
//line pages/account/password/change/change.qtpl:1
}

//line pages/account/password/change/change.qtpl:3
func (p *Page) StreamContent(qw422016 *qt422016.Writer) {
//line pages/account/password/change/change.qtpl:3
	qw422016.N().S(`<div class="account"><div class="accountSb">`)
//line pages/account/password/change/change.qtpl:5
	qw422016.N().S(p.rendererService.AccountMenu(p.GetCoreContext()))
//line pages/account/password/change/change.qtpl:5
	qw422016.N().S(`</div><div class="accountH"><h1>`)
//line pages/account/password/change/change.qtpl:7
	qw422016.E().S(p.Translate("account"))
//line pages/account/password/change/change.qtpl:7
	qw422016.N().S(`</h1></div><div class="accountC"><h2>`)
//line pages/account/password/change/change.qtpl:10
	qw422016.E().S(p.Translate("changePassword"))
//line pages/account/password/change/change.qtpl:10
	qw422016.N().S(`</h2>`)
//line pages/account/password/change/change.qtpl:12
	if p.HasFlashMessage() {
//line pages/account/password/change/change.qtpl:12
		qw422016.N().S(`<p class="`)
//line pages/account/password/change/change.qtpl:13
		qw422016.E().S(p.GetFlashMessage().ClassName())
//line pages/account/password/change/change.qtpl:13
		qw422016.N().S(`"><span>×</span>`)
//line pages/account/password/change/change.qtpl:15
		qw422016.E().S(p.GetFlashMessage().Icon())
//line pages/account/password/change/change.qtpl:15
		qw422016.E().S(p.GetFlashMessage().Message())
//line pages/account/password/change/change.qtpl:15
		qw422016.N().S(`</p>`)
//line pages/account/password/change/change.qtpl:17
	}
//line pages/account/password/change/change.qtpl:19
	qw422016.N().S(p.form.Errors())
//line pages/account/password/change/change.qtpl:20
	qw422016.N().S(p.form.Open())
//line pages/account/password/change/change.qtpl:21
	qw422016.N().S(p.form.Field("_uname"))
//line pages/account/password/change/change.qtpl:22
	qw422016.N().S(p.form.Field("_t"))
//line pages/account/password/change/change.qtpl:23
	qw422016.N().S(p.form.Field("currentPassword"))
//line pages/account/password/change/change.qtpl:23
	qw422016.N().S(`<br>`)
//line pages/account/password/change/change.qtpl:24
	qw422016.N().S(p.form.Field("newPassword"))
//line pages/account/password/change/change.qtpl:24
	qw422016.N().S(`<br>`)
//line pages/account/password/change/change.qtpl:25
	qw422016.N().S(p.form.Field("repeatNewPassword"))
//line pages/account/password/change/change.qtpl:25
	qw422016.N().S(`<br><input type="submit" value="`)
//line pages/account/password/change/change.qtpl:26
	qw422016.E().S(p.Translate("changePassword"))
//line pages/account/password/change/change.qtpl:26
	qw422016.N().S(`"></form></div></div>`)
//line pages/account/password/change/change.qtpl:30
}

//line pages/account/password/change/change.qtpl:30
func (p *Page) WriteContent(qq422016 qtio422016.Writer) {
//line pages/account/password/change/change.qtpl:30
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/account/password/change/change.qtpl:30
	p.StreamContent(qw422016)
//line pages/account/password/change/change.qtpl:30
	qt422016.ReleaseWriter(qw422016)
//line pages/account/password/change/change.qtpl:30
}

//line pages/account/password/change/change.qtpl:30
func (p *Page) Content() string {
//line pages/account/password/change/change.qtpl:30
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/account/password/change/change.qtpl:30
	p.WriteContent(qb422016)
//line pages/account/password/change/change.qtpl:30
	qs422016 := string(qb422016.B)
//line pages/account/password/change/change.qtpl:30
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/account/password/change/change.qtpl:30
	return qs422016
//line pages/account/password/change/change.qtpl:30
}

//line pages/account/password/change/change.qtpl:32
func (p *Page) StreamStylesheets(qw422016 *qt422016.Writer) {
//line pages/account/password/change/change.qtpl:32
	qw422016.N().S(`<link rel="stylesheet" href="/c/account.css">`)
//line pages/account/password/change/change.qtpl:34
}

//line pages/account/password/change/change.qtpl:34
func (p *Page) WriteStylesheets(qq422016 qtio422016.Writer) {
//line pages/account/password/change/change.qtpl:34
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/account/password/change/change.qtpl:34
	p.StreamStylesheets(qw422016)
//line pages/account/password/change/change.qtpl:34
	qt422016.ReleaseWriter(qw422016)
//line pages/account/password/change/change.qtpl:34
}

//line pages/account/password/change/change.qtpl:34
func (p *Page) Stylesheets() string {
//line pages/account/password/change/change.qtpl:34
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/account/password/change/change.qtpl:34
	p.WriteStylesheets(qb422016)
//line pages/account/password/change/change.qtpl:34
	qs422016 := string(qb422016.B)
//line pages/account/password/change/change.qtpl:34
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/account/password/change/change.qtpl:34
	return qs422016
//line pages/account/password/change/change.qtpl:34
}
