// Code generated by qtc from "createupdate.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line pages/admin/user/contact/createupdate/createupdate.qtpl:1
package createupdate

//line pages/admin/user/contact/createupdate/createupdate.qtpl:1
import "fmt"

//line pages/admin/user/contact/createupdate/createupdate.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line pages/admin/user/contact/createupdate/createupdate.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line pages/admin/user/contact/createupdate/createupdate.qtpl:3
func (p *Page) StreamTitle(qw422016 *qt422016.Writer) {
//line pages/admin/user/contact/createupdate/createupdate.qtpl:3
	qw422016.E().S(p.displayTitle)
//line pages/admin/user/contact/createupdate/createupdate.qtpl:3
}

//line pages/admin/user/contact/createupdate/createupdate.qtpl:3
func (p *Page) WriteTitle(qq422016 qtio422016.Writer) {
//line pages/admin/user/contact/createupdate/createupdate.qtpl:3
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/admin/user/contact/createupdate/createupdate.qtpl:3
	p.StreamTitle(qw422016)
//line pages/admin/user/contact/createupdate/createupdate.qtpl:3
	qt422016.ReleaseWriter(qw422016)
//line pages/admin/user/contact/createupdate/createupdate.qtpl:3
}

//line pages/admin/user/contact/createupdate/createupdate.qtpl:3
func (p *Page) Title() string {
//line pages/admin/user/contact/createupdate/createupdate.qtpl:3
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/admin/user/contact/createupdate/createupdate.qtpl:3
	p.WriteTitle(qb422016)
//line pages/admin/user/contact/createupdate/createupdate.qtpl:3
	qs422016 := string(qb422016.B)
//line pages/admin/user/contact/createupdate/createupdate.qtpl:3
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/admin/user/contact/createupdate/createupdate.qtpl:3
	return qs422016
//line pages/admin/user/contact/createupdate/createupdate.qtpl:3
}

//line pages/admin/user/contact/createupdate/createupdate.qtpl:5
func (p *Page) StreamContent(qw422016 *qt422016.Writer) {
//line pages/admin/user/contact/createupdate/createupdate.qtpl:5
	qw422016.N().S(`<main class="content"><h1>`)
//line pages/admin/user/contact/createupdate/createupdate.qtpl:7
	qw422016.E().S(p.displayTitle)
//line pages/admin/user/contact/createupdate/createupdate.qtpl:7
	qw422016.N().S(`</h1>`)
//line pages/admin/user/contact/createupdate/createupdate.qtpl:8
	qw422016.N().S(p.form.Errors())
//line pages/admin/user/contact/createupdate/createupdate.qtpl:9
	qw422016.N().S(p.rendererService.CreatedUpdatedByLinks(p.GetCoreContext(), p.language.ID(), p.userContact))
//line pages/admin/user/contact/createupdate/createupdate.qtpl:10
	qw422016.N().S(p.form.Open())
//line pages/admin/user/contact/createupdate/createupdate.qtpl:11
	qw422016.N().S(p.form.Field("_uname"))
//line pages/admin/user/contact/createupdate/createupdate.qtpl:12
	qw422016.N().S(p.form.Field("_t"))
//line pages/admin/user/contact/createupdate/createupdate.qtpl:13
	qw422016.N().S(p.form.Field("sorting"))
//line pages/admin/user/contact/createupdate/createupdate.qtpl:13
	qw422016.N().S(`<br>`)
//line pages/admin/user/contact/createupdate/createupdate.qtpl:14
	qw422016.N().S(p.form.Field("contact"))
//line pages/admin/user/contact/createupdate/createupdate.qtpl:14
	qw422016.N().S(`<br>`)
//line pages/admin/user/contact/createupdate/createupdate.qtpl:15
	qw422016.N().S(p.form.Field("comment"))
//line pages/admin/user/contact/createupdate/createupdate.qtpl:15
	qw422016.N().S(`<br>`)
//line pages/admin/user/contact/createupdate/createupdate.qtpl:16
	qw422016.N().S(p.form.CreateUpdateActions("action", fmt.Sprintf("User/View?id=%s", p.user.ID())))
//line pages/admin/user/contact/createupdate/createupdate.qtpl:16
	qw422016.N().S(`</form></main>`)
//line pages/admin/user/contact/createupdate/createupdate.qtpl:19
}

//line pages/admin/user/contact/createupdate/createupdate.qtpl:19
func (p *Page) WriteContent(qq422016 qtio422016.Writer) {
//line pages/admin/user/contact/createupdate/createupdate.qtpl:19
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/admin/user/contact/createupdate/createupdate.qtpl:19
	p.StreamContent(qw422016)
//line pages/admin/user/contact/createupdate/createupdate.qtpl:19
	qt422016.ReleaseWriter(qw422016)
//line pages/admin/user/contact/createupdate/createupdate.qtpl:19
}

//line pages/admin/user/contact/createupdate/createupdate.qtpl:19
func (p *Page) Content() string {
//line pages/admin/user/contact/createupdate/createupdate.qtpl:19
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/admin/user/contact/createupdate/createupdate.qtpl:19
	p.WriteContent(qb422016)
//line pages/admin/user/contact/createupdate/createupdate.qtpl:19
	qs422016 := string(qb422016.B)
//line pages/admin/user/contact/createupdate/createupdate.qtpl:19
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/admin/user/contact/createupdate/createupdate.qtpl:19
	return qs422016
//line pages/admin/user/contact/createupdate/createupdate.qtpl:19
}

//line pages/admin/user/contact/createupdate/createupdate.qtpl:21
func (p *Page) StreamStylesheets(qw422016 *qt422016.Writer) {
//line pages/admin/user/contact/createupdate/createupdate.qtpl:22
	if p.form.ContainsSelectSearch() {
//line pages/admin/user/contact/createupdate/createupdate.qtpl:22
		qw422016.N().S(`<link rel="stylesheet" href="/c/a/selectSearch.css"></link>`)
//line pages/admin/user/contact/createupdate/createupdate.qtpl:24
	}
//line pages/admin/user/contact/createupdate/createupdate.qtpl:25
}

//line pages/admin/user/contact/createupdate/createupdate.qtpl:25
func (p *Page) WriteStylesheets(qq422016 qtio422016.Writer) {
//line pages/admin/user/contact/createupdate/createupdate.qtpl:25
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/admin/user/contact/createupdate/createupdate.qtpl:25
	p.StreamStylesheets(qw422016)
//line pages/admin/user/contact/createupdate/createupdate.qtpl:25
	qt422016.ReleaseWriter(qw422016)
//line pages/admin/user/contact/createupdate/createupdate.qtpl:25
}

//line pages/admin/user/contact/createupdate/createupdate.qtpl:25
func (p *Page) Stylesheets() string {
//line pages/admin/user/contact/createupdate/createupdate.qtpl:25
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/admin/user/contact/createupdate/createupdate.qtpl:25
	p.WriteStylesheets(qb422016)
//line pages/admin/user/contact/createupdate/createupdate.qtpl:25
	qs422016 := string(qb422016.B)
//line pages/admin/user/contact/createupdate/createupdate.qtpl:25
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/admin/user/contact/createupdate/createupdate.qtpl:25
	return qs422016
//line pages/admin/user/contact/createupdate/createupdate.qtpl:25
}

//line pages/admin/user/contact/createupdate/createupdate.qtpl:27
func (p *Page) StreamJavascripts(qw422016 *qt422016.Writer) {
//line pages/admin/user/contact/createupdate/createupdate.qtpl:27
	qw422016.N().S(`<script src="/j/a/cu.js"></script>`)
//line pages/admin/user/contact/createupdate/createupdate.qtpl:29
	if p.form.ContainsSelectSearch() {
//line pages/admin/user/contact/createupdate/createupdate.qtpl:29
		qw422016.N().S(`<script src="/j/a/selectSearch.js"></script>`)
//line pages/admin/user/contact/createupdate/createupdate.qtpl:31
	}
//line pages/admin/user/contact/createupdate/createupdate.qtpl:32
}

//line pages/admin/user/contact/createupdate/createupdate.qtpl:32
func (p *Page) WriteJavascripts(qq422016 qtio422016.Writer) {
//line pages/admin/user/contact/createupdate/createupdate.qtpl:32
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pages/admin/user/contact/createupdate/createupdate.qtpl:32
	p.StreamJavascripts(qw422016)
//line pages/admin/user/contact/createupdate/createupdate.qtpl:32
	qt422016.ReleaseWriter(qw422016)
//line pages/admin/user/contact/createupdate/createupdate.qtpl:32
}

//line pages/admin/user/contact/createupdate/createupdate.qtpl:32
func (p *Page) Javascripts() string {
//line pages/admin/user/contact/createupdate/createupdate.qtpl:32
	qb422016 := qt422016.AcquireByteBuffer()
//line pages/admin/user/contact/createupdate/createupdate.qtpl:32
	p.WriteJavascripts(qb422016)
//line pages/admin/user/contact/createupdate/createupdate.qtpl:32
	qs422016 := string(qb422016.B)
//line pages/admin/user/contact/createupdate/createupdate.qtpl:32
	qt422016.ReleaseByteBuffer(qb422016)
//line pages/admin/user/contact/createupdate/createupdate.qtpl:32
	return qs422016
//line pages/admin/user/contact/createupdate/createupdate.qtpl:32
}
